// <autogenerated>
//   This file was generated by T4 code generator GeneratePartyDomain.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


package org.dddml.wms.domain.party;

public class PartyTypeIds
{

		
    public static final String PARTY = "Party";

		
    public static final String ORGANIZATION = "Organization";

}

