// <autogenerated>
//   This file was generated by T4 code generator GenerateBoundedContextDomain.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


package org.dddml.wms.domain;

public class DocumentAction {


    public static final String DRAFT = "Draft";


    public static final String COMPLETE = "Complete";


    public static final String VOID = "Void";


    public static final String CLOSE = "Close";


    public static final String REVERSE = "Reverse";


    public static final String CONFIRM = "Confirm";

}

