// <autogenerated>
//   This file was generated by T4 code generator GenerateUomOfbizDataConstObjects.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

package org.dddml.wms.domain.uom;

public class UomIds {
    /**
     * Costa Rica Colon.
     */
    public static final String CRC = "CRC";

    /**
     * Colombian Peso.
     */
    public static final String COP = "COP";

    /**
     * China.
     */
    public static final String CNY = "CNY";

    /**
     * Chilean Peso.
     */
    public static final String CLP = "CLP";

    /**
     * Swiss Franc.
     */
    public static final String CHF = "CHF";

    /**
     * Santo Domiongo.
     */
    public static final String CDP = "CDP";

    /**
     * Canadian Dollar.
     */
    public static final String CAD = "CAD";

    /**
     * Belize Dollar.
     */
    public static final String BZD = "BZD";

    /**
     * Belorussian Ruble.
     */
    public static final String BYR = "BYR";

    /**
     * Botswana Pula.
     */
    public static final String BWP = "BWP";

    /**
     * Bahaman Dollar.
     */
    public static final String BSD = "BSD";

    /**
     * Brazil.
     */
    public static final String BRR = "BRR";

    /**
     * Brazilian Real.
     */
    public static final String BRL = "BRL";

    /**
     * Bolivian Boliviano.
     */
    public static final String BOB = "BOB";

    /**
     * Brunei Dollar.
     */
    public static final String BND = "BND";

    /**
     * Bermudan Dollar.
     */
    public static final String BMD = "BMD";

    /**
     * Burundi Franc.
     */
    public static final String BIF = "BIF";

    /**
     * Bahrain Dinar.
     */
    public static final String BHD = "BHD";

    /**
     * Bulgarian Lev.
     */
    public static final String BGN = "BGN";

    /**
     * Bangladesh Taka.
     */
    public static final String BDT = "BDT";

    /**
     * Barbados Dollar.
     */
    public static final String BBD = "BBD";

    /**
     * Bosnia-Herzogovinian Dinar.
     */
    public static final String BAD = "BAD";

    /**
     * Azerbaijan Manat.
     */
    public static final String AZM = "AZM";

    /**
     * Aruban Guilder.
     */
    public static final String AWG = "AWG";

    /**
     * Australian Dollar.
     */
    public static final String AUD = "AUD";

    /**
     * Argentina Peso.
     */
    public static final String ARS = "ARS";

    /**
     * Argentinian Austral.
     */
    public static final String ARA = "ARA";

    /**
     * Angolan Kwanza.
     */
    public static final String AOK = "AOK";

    /**
     * West Indian Guilder.
     */
    public static final String ANG = "ANG";

    /**
     * Armenian Dram.
     */
    public static final String AMD = "AMD";

    /**
     * Albanian Lek.
     */
    public static final String ALL = "ALL";

    /**
     * Afghani.
     */
    public static final String AFA = "AFA";

    /**
     * United Arab Emirates Dirham.
     */
    public static final String AED = "AED";

    /**
     * Andoran peseta.
     */
    public static final String ADP = "ADP";

    /**
     * Cuban Peso.
     */
    public static final String CUP = "CUP";

    /**
     * Cape Verde Escudo.
     */
    public static final String CVE = "CVE";

    /**
     * Cyprus Pound.
     */
    public static final String CYP = "CYP";

    /**
     * Czech Koruna.
     */
    public static final String CZK = "CZK";

    /**
     * Djibouti Franc.
     */
    public static final String DJF = "DJF";

    /**
     * Danish Krone.
     */
    public static final String DKK = "DKK";

    /**
     * Dominican Peso.
     */
    public static final String DOP = "DOP";

    /**
     * Dominican Republic Peso.
     */
    public static final String DRP = "DRP";

    /**
     * Algerian Dinar.
     */
    public static final String DZD = "DZD";

    /**
     * Ecuador Sucre.
     */
    public static final String ECS = "ECS";

    /**
     * Estonian Krone.
     */
    public static final String EEK = "EEK";

    /**
     * Egyptian Pound.
     */
    public static final String EGP = "EGP";

    /**
     * Ethiopian Birr.
     */
    public static final String ETB = "ETB";

    /**
     * Euro.
     */
    public static final String EUR = "EUR";

    /**
     * Fiji Dollar.
     */
    public static final String FJD = "FJD";

    /**
     * Falkland Pound.
     */
    public static final String FKP = "FKP";

    /**
     * British Pound.
     */
    public static final String GBP = "GBP";

    /**
     * Georgian Kupon.
     */
    public static final String GEK = "GEK";

    /**
     * Ghanian Cedi.
     */
    public static final String GHC = "GHC";

    /**
     * Gibraltar Pound.
     */
    public static final String GIP = "GIP";

    /**
     * Gambian Dalasi.
     */
    public static final String GMD = "GMD";

    /**
     * Guinea Franc.
     */
    public static final String GNF = "GNF";

    /**
     * Guatemalan Quedzal.
     */
    public static final String GTQ = "GTQ";

    /**
     * Guinea Peso.
     */
    public static final String GWP = "GWP";

    /**
     * Guyanese Dollar.
     */
    public static final String GYD = "GYD";

    /**
     * Hong Kong Dollar.
     */
    public static final String HKD = "HKD";

    /**
     * Honduran Lempira.
     */
    public static final String HNL = "HNL";

    /**
     * Croatian Kuna.
     */
    public static final String HRK = "HRK";

    /**
     * Haitian Gourde.
     */
    public static final String HTG = "HTG";

    /**
     * Hungarian forint.
     */
    public static final String HUF = "HUF";

    /**
     * Indeonesian Rupiah.
     */
    public static final String IDR = "IDR";

    /**
     * Indian Rupee.
     */
    public static final String INR = "INR";

    /**
     * Iraqui Dinar.
     */
    public static final String IQD = "IQD";

    /**
     * Iranian Rial.
     */
    public static final String IRR = "IRR";

    /**
     * Iceland Krona.
     */
    public static final String ISK = "ISK";

    /**
     * Jamaican Dollar.
     */
    public static final String JMD = "JMD";

    /**
     * Jordanian Dinar.
     */
    public static final String JOD = "JOD";

    /**
     * Japanese Yen.
     */
    public static final String JPY = "JPY";

    /**
     * Kenyan Shilling.
     */
    public static final String KES = "KES";

    /**
     * Cambodian Riel.
     */
    public static final String KHR = "KHR";

    /**
     * Kirghizstan Som.
     */
    public static final String KIS = "KIS";

    /**
     * Comoros Franc.
     */
    public static final String KMF = "KMF";

    /**
     * North Korean Won.
     */
    public static final String KPW = "KPW";

    /**
     * South Korean Won.
     */
    public static final String KRW = "KRW";

    /**
     * Kuwaiti Dinar.
     */
    public static final String KWD = "KWD";

    /**
     * Cayman Dollar.
     */
    public static final String KYD = "KYD";

    /**
     * Kazakhstani Tenge.
     */
    public static final String KZT = "KZT";

    /**
     * Laotian Kip.
     */
    public static final String LAK = "LAK";

    /**
     * Lebanese Pound.
     */
    public static final String LBP = "LBP";

    /**
     * Sri Lankan Rupee.
     */
    public static final String LKR = "LKR";

    /**
     * Liberian Dollar.
     */
    public static final String LRD = "LRD";

    /**
     * Lesotho Loti.
     */
    public static final String LSL = "LSL";

    /**
     * Lithuanian Lita.
     */
    public static final String LTL = "LTL";

    /**
     * Latvian Lat.
     */
    public static final String LVL = "LVL";

    /**
     * Libyan Dinar.
     */
    public static final String LYD = "LYD";

    /**
     * Moroccan Dirham.
     */
    public static final String MAD = "MAD";

    /**
     * Moldavian Lei.
     */
    public static final String MDL = "MDL";

    /**
     * Madagascan Franc.
     */
    public static final String MGF = "MGF";

    /**
     * Mongolian Tugrik.
     */
    public static final String MNT = "MNT";

    /**
     * Macao Pataca.
     */
    public static final String MOP = "MOP";

    /**
     * Mauritanian Ouguiya.
     */
    public static final String MRO = "MRO";

    /**
     * Maltese Lira.
     */
    public static final String MTL = "MTL";

    /**
     * Mauritius Rupee.
     */
    public static final String MUR = "MUR";

    /**
     * Maldive Rufiyaa.
     */
    public static final String MVR = "MVR";

    /**
     * Malawi Kwacha.
     */
    public static final String MWK = "MWK";

    /**
     * Mexican Peso (new).
     */
    public static final String MXN = "MXN";

    /**
     * Mexican Peso (old).
     */
    public static final String MXP = "MXP";

    /**
     * Malaysian Ringgit.
     */
    public static final String MYR = "MYR";

    /**
     * Mozambique Metical.
     */
    public static final String MZM = "MZM";

    /**
     * Nigerian Naira.
     */
    public static final String NGN = "NGN";

    /**
     * Nicaragua.
     */
    public static final String NIC = "NIC";

    /**
     * Nicaraguan Cordoba.
     */
    public static final String NIO = "NIO";

    /**
     * New Israeli Shekel.
     */
    public static final String NIS = "NIS";

    /**
     * Norwegian Krone.
     */
    public static final String NOK = "NOK";

    /**
     * Nepalese Rupee.
     */
    public static final String NPR = "NPR";

    /**
     * New Zealand Dollar.
     */
    public static final String NZD = "NZD";

    /**
     * Omani Rial.
     */
    public static final String OMR = "OMR";

    /**
     * Panamanian Balboa.
     */
    public static final String PAB = "PAB";

    /**
     * Peruvian Inti.
     */
    public static final String PEI = "PEI";

    /**
     * Peruvian Sol - New.
     */
    public static final String PEN = "PEN";

    /**
     * Peruvian Sol.
     */
    public static final String PES = "PES";

    /**
     * Papua New Guinea Kina.
     */
    public static final String PGK = "PGK";

    /**
     * Philippino Peso.
     */
    public static final String PHP = "PHP";

    /**
     * Pakistan Rupee.
     */
    public static final String PKR = "PKR";

    /**
     * Polish Zloty.
     */
    public static final String PLN = "PLN";

    /**
     * Poland.
     */
    public static final String PLZ = "PLZ";

    /**
     * Paraguayan Guarani.
     */
    public static final String PYG = "PYG";

    /**
     * Qatar Riyal.
     */
    public static final String QAR = "QAR";

    /**
     * Romanian Leu.
     */
    public static final String ROL = "ROL";

    /**
     * Russian Rouble.
     */
    public static final String RUR = "RUR";

    /**
     * Rwanda Franc.
     */
    public static final String RWF = "RWF";

    /**
     * Saudi Riyal.
     */
    public static final String SAR = "SAR";

    /**
     * Solomon Islands Dollar.
     */
    public static final String SBD = "SBD";

    /**
     * Seychelles Rupee.
     */
    public static final String SCR = "SCR";

    /**
     * Sudanese Pound.
     */
    public static final String SDP = "SDP";

    /**
     * Swedish Krona.
     */
    public static final String SEK = "SEK";

    /**
     * Singapore Dollar.
     */
    public static final String SGD = "SGD";

    /**
     * St.Helena Pound.
     */
    public static final String SHP = "SHP";

    /**
     * Leone.
     */
    public static final String SLL = "SLL";

    /**
     * Peru.
     */
    public static final String SOL = "SOL";

    /**
     * Somalian Shilling.
     */
    public static final String SOS = "SOS";

    /**
     * Surinam Guilder.
     */
    public static final String SRG = "SRG";

    /**
     * Sao Tome / Principe Dobra.
     */
    public static final String STD = "STD";

    /**
     * Russian Ruble (old).
     */
    public static final String SUR = "SUR";

    /**
     * El Salvador Colon.
     */
    public static final String SVC = "SVC";

    /**
     * Syrian Pound.
     */
    public static final String SYP = "SYP";

    /**
     * Swaziland Lilangeni.
     */
    public static final String SZL = "SZL";

    /**
     * Thailand Baht.
     */
    public static final String THB = "THB";

    /**
     * Tadzhikistani Ruble.
     */
    public static final String TJR = "TJR";

    /**
     * Turkmenistani Manat.
     */
    public static final String TMM = "TMM";

    /**
     * Tunisian Dinar.
     */
    public static final String TND = "TND";

    /**
     * Tongan Pa'anga.
     */
    public static final String TOP = "TOP";

    /**
     * Timor Escudo.
     */
    public static final String TPE = "TPE";

    /**
     * Turkish Lira.
     */
    public static final String TRY = "TRY";

    /**
     * Trinidad and Tobago Dollar.
     */
    public static final String TTD = "TTD";

    /**
     * New Taiwan Dollar.
     */
    public static final String TWD = "TWD";

    /**
     * Tanzanian Shilling.
     */
    public static final String TZS = "TZS";

    /**
     * Ukrainian Hryvnia.
     */
    public static final String UAH = "UAH";

    /**
     * Ugandan Shilling.
     */
    public static final String UGS = "UGS";

    /**
     * United States Dollar.
     */
    public static final String USD = "USD";

    /**
     * Uruguayan New Peso.
     */
    public static final String UYP = "UYP";

    /**
     * Uruguay.
     */
    public static final String UYU = "UYU";

    /**
     * Venezuelan Bolivar.
     */
    public static final String VEB = "VEB";

    /**
     * Vietnamese Dong.
     */
    public static final String VND = "VND";

    /**
     * Vanuatu Vatu.
     */
    public static final String VUV = "VUV";

    /**
     * Samoan Tala.
     */
    public static final String WST = "WST";

    /**
     * Gabon C.f.A Franc.
     */
    public static final String XAF = "XAF";

    /**
     * East Carribean Dollar.
     */
    public static final String XCD = "XCD";

    /**
     * Benin C.f.A. Franc.
     */
    public static final String XOF = "XOF";

    /**
     * Yemeni Ryal.
     */
    public static final String YER = "YER";

    /**
     * South African Rand.
     */
    public static final String ZAR = "ZAR";

    /**
     * Zambian Kwacha.
     */
    public static final String ZMK = "ZMK";

    /**
     * Zaire.
     */
    public static final String ZRZ = "ZRZ";

    /**
     * Zimbabwean Dollar.
     */
    public static final String ZWD = "ZWD";

    /**
     * Bit of Data.
     */
    public static final String DATA_b = "DATA_b";

    /**
     * Kilobit of Data.
     */
    public static final String DATA_Kb = "DATA_Kb";

    /**
     * Megabit of Data.
     */
    public static final String DATA_Mb = "DATA_Mb";

    /**
     * Gigabit of Data.
     */
    public static final String DATA_Gb = "DATA_Gb";

    /**
     * Terabit of Data.
     */
    public static final String DATA_Tb = "DATA_Tb";

    /**
     * Petabit of Data.
     */
    public static final String DATA_Pb = "DATA_Pb";

    /**
     * Byte of Data.
     */
    public static final String DATA_B = "DATA_B";

    /**
     * Kilobyte of Data.
     */
    public static final String DATA_KB = "DATA_KB";

    /**
     * Megabyte of Data.
     */
    public static final String DATA_MB = "DATA_MB";

    /**
     * Gigabyte of Data.
     */
    public static final String DATA_GB = "DATA_GB";

    /**
     * Terabyte of Data.
     */
    public static final String DATA_TB = "DATA_TB";

    /**
     * Petabyte of Data.
     */
    public static final String DATA_PB = "DATA_PB";

    /**
     * Bit-per-second of Data.
     */
    public static final String DATASPD_bps = "DATASPD_bps";

    /**
     * Kilobit-per-second of Data.
     */
    public static final String DATASPD_Kbps = "DATASPD_Kbps";

    /**
     * Megabit-per-second of Data.
     */
    public static final String DATASPD_Mbps = "DATASPD_Mbps";

    /**
     * Gigabit-per-second of Data.
     */
    public static final String DATASPD_Gbps = "DATASPD_Gbps";

    /**
     * Terabit-per-second of Data.
     */
    public static final String DATASPD_Tbps = "DATASPD_Tbps";

    /**
     * Time in Milli-Seconds.
     */
    public static final String TF_ms = "TF_ms";

    /**
     * Time in Seconds.
     */
    public static final String TF_s = "TF_s";

    /**
     * Time in Minutes.
     */
    public static final String TF_min = "TF_min";

    /**
     * Time in Hours.
     */
    public static final String TF_hr = "TF_hr";

    /**
     * Time in Days.
     */
    public static final String TF_day = "TF_day";

    /**
     * Time in Weeks.
     */
    public static final String TF_wk = "TF_wk";

    /**
     * Time in Months.
     */
    public static final String TF_mon = "TF_mon";

    /**
     * Time in Years.
     */
    public static final String TF_yr = "TF_yr";

    /**
     * Time in Decades.
     */
    public static final String TF_decade = "TF_decade";

    /**
     * Time in Scores.
     */
    public static final String TF_score = "TF_score";

    /**
     * Time in Centuries.
     */
    public static final String TF_century = "TF_century";

    /**
     * Time in Millenia.
     */
    public static final String TF_millenium = "TF_millenium";

    /**
     * Angstrom.
     */
    public static final String LEN_A = "LEN_A";

    /**
     * Cable.
     */
    public static final String LEN_cb = "LEN_cb";

    /**
     * Centimeter.
     */
    public static final String LEN_cm = "LEN_cm";

    /**
     * Chain (Gunter's/surveyor's).
     */
    public static final String LEN_chG = "LEN_chG";

    /**
     * Chain (Ramden's/engineer's).
     */
    public static final String LEN_chR = "LEN_chR";

    /**
     * Decimeter.
     */
    public static final String LEN_dm = "LEN_dm";

    /**
     * Dekameter.
     */
    public static final String LEN_dam = "LEN_dam";

    /**
     * Fathom.
     */
    public static final String LEN_fm = "LEN_fm";

    /**
     * Foot.
     */
    public static final String LEN_ft = "LEN_ft";

    /**
     * Furlong.
     */
    public static final String LEN_fur = "LEN_fur";

    /**
     * Hand (horse's height).
     */
    public static final String LEN_hand = "LEN_hand";

    /**
     * Inch.
     */
    public static final String LEN_in = "LEN_in";

    /**
     * Kilometer.
     */
    public static final String LEN_km = "LEN_km";

    /**
     * League.
     */
    public static final String LEN_league = "LEN_league";

    /**
     * Link (Gunter's).
     */
    public static final String LEN_lnG = "LEN_lnG";

    /**
     * Link (Ramden's).
     */
    public static final String LEN_lnR = "LEN_lnR";

    /**
     * Meter.
     */
    public static final String LEN_m = "LEN_m";

    /**
     * Micrometer (Micron).
     */
    public static final String LEN_u = "LEN_u";

    /**
     * Mile (statute/land).
     */
    public static final String LEN_mi = "LEN_mi";

    /**
     * Mile (nautical/sea).
     */
    public static final String LEN_nmi = "LEN_nmi";

    /**
     * Millimeter.
     */
    public static final String LEN_mm = "LEN_mm";

    /**
     * Mil (Milli-inch).
     */
    public static final String LEN_mil = "LEN_mil";

    /**
     * Point (type size).
     */
    public static final String LEN_point = "LEN_point";

    /**
     * Pica (type size).
     */
    public static final String LEN_pica = "LEN_pica";

    /**
     * Rod.
     */
    public static final String LEN_rd = "LEN_rd";

    /**
     * Yard.
     */
    public static final String LEN_yd = "LEN_yd";

    /**
     * Acre.
     */
    public static final String AREA_A = "AREA_A";

    /**
     * Are.
     */
    public static final String AREA_a = "AREA_a";

    /**
     * Hectare.
     */
    public static final String AREA_ha = "AREA_ha";

    /**
     * Square Centimeter.
     */
    public static final String AREA_cm2 = "AREA_cm2";

    /**
     * Square Foot.
     */
    public static final String AREA_ft2 = "AREA_ft2";

    /**
     * Square Inch.
     */
    public static final String AREA_in2 = "AREA_in2";

    /**
     * Square Kilometer.
     */
    public static final String AREA_km2 = "AREA_km2";

    /**
     * Square Meter.
     */
    public static final String AREA_m2 = "AREA_m2";

    /**
     * Square Mile.
     */
    public static final String AREA_mi2 = "AREA_mi2";

    /**
     * Square Millimeter.
     */
    public static final String AREA_mm2 = "AREA_mm2";

    /**
     * Square Rod.
     */
    public static final String AREA_rd2 = "AREA_rd2";

    /**
     * Square Yard.
     */
    public static final String AREA_yd2 = "AREA_yd2";

    /**
     * Barrel (US).
     */
    public static final String VLIQ_bbl = "VLIQ_bbl";

    /**
     * Cup.
     */
    public static final String VLIQ_cup = "VLIQ_cup";

    /**
     * Dram (US).
     */
    public static final String VLIQ_dr = "VLIQ_dr";

    /**
     * Gill (1/4 UK pint).
     */
    public static final String VLIQ_gi = "VLIQ_gi";

    /**
     * Gallon (UK).
     */
    public static final String VLIQ_galUK = "VLIQ_galUK";

    /**
     * Gallon (US).
     */
    public static final String VLIQ_galUS = "VLIQ_galUS";

    /**
     * Cubic meter (liquid).
     */
    public static final String VLIQ_M3 = "VLIQ_M3";

    /**
     * Hectoliter.
     */
    public static final String VLIQ_HL = "VLIQ_HL";

    /**
     * Liter.
     */
    public static final String VLIQ_L = "VLIQ_L";

    /**
     * Milliliter.
     */
    public static final String VLIQ_ml = "VLIQ_ml";

    /**
     * Ounce, fluid (UK).
     */
    public static final String VLIQ_ozUK = "VLIQ_ozUK";

    /**
     * Ounce, fluid (US).
     */
    public static final String VLIQ_ozUS = "VLIQ_ozUS";

    /**
     * Pint (UK).
     */
    public static final String VLIQ_ptUK = "VLIQ_ptUK";

    /**
     * Pint (US).
     */
    public static final String VLIQ_ptUS = "VLIQ_ptUS";

    /**
     * Quart.
     */
    public static final String VLIQ_qt = "VLIQ_qt";

    /**
     * Tablespoon.
     */
    public static final String VLIQ_Tbs = "VLIQ_Tbs";

    /**
     * Teaspoon.
     */
    public static final String VLIQ_tsp = "VLIQ_tsp";

    /**
     * Cubic centimeter.
     */
    public static final String VDRY_cm3 = "VDRY_cm3";

    /**
     * Cubic foot.
     */
    public static final String VDRY_ft3 = "VDRY_ft3";

    /**
     * Cubic inch.
     */
    public static final String VDRY_in3 = "VDRY_in3";

    /**
     * Cubic meter.
     */
    public static final String VDRY_m3 = "VDRY_m3";

    /**
     * Cubic millimeter.
     */
    public static final String VDRY_mm3 = "VDRY_mm3";

    /**
     * Stere (cubic meter).
     */
    public static final String VDRY_ST = "VDRY_ST";

    /**
     * Cubic yard.
     */
    public static final String VDRY_yd3 = "VDRY_yd3";

    /**
     * Dram (avdp).
     */
    public static final String WT_dr_avdp = "WT_dr_avdp";

    /**
     * Grain.
     */
    public static final String WT_gr = "WT_gr";

    /**
     * Gram.
     */
    public static final String WT_g = "WT_g";

    /**
     * Kilogram.
     */
    public static final String WT_kg = "WT_kg";

    /**
     * Milligram.
     */
    public static final String WT_mg = "WT_mg";

    /**
     * Ounce (avdp).
     */
    public static final String WT_oz = "WT_oz";

    /**
     * Ounce (troy).
     */
    public static final String WT_oz_tr = "WT_oz_tr";

    /**
     * Pennyweight.
     */
    public static final String WT_dwt = "WT_dwt";

    /**
     * Pound (avdp).
     */
    public static final String WT_lb = "WT_lb";

    /**
     * Stone.
     */
    public static final String WT_st = "WT_st";

    /**
     * Ton (long or British).
     */
    public static final String WT_lt = "WT_lt";

    /**
     * Ton (metric).
     */
    public static final String WT_mt = "WT_mt";

    /**
     * Ton (short or US).
     */
    public static final String WT_sh_t = "WT_sh_t";

    /**
     * British Thermal Unit.
     */
    public static final String EN_Btu = "EN_Btu";

    /**
     * Calorie (@15.5c).
     */
    public static final String EN_cal15 = "EN_cal15";

    /**
     * Horsepower (mechanical).
     */
    public static final String EN_HP = "EN_HP";

    /**
     * Joule (absolute).
     */
    public static final String EN_J = "EN_J";

    /**
     * Kilowatt.
     */
    public static final String EN_Kw = "EN_Kw";

    /**
     * Watt.
     */
    public static final String EN_w = "EN_w";

    /**
     * Kelvin.
     */
    public static final String TEMP_K = "TEMP_K";

    /**
     * Degrees Celsius.
     */
    public static final String TEMP_C = "TEMP_C";

    /**
     * Degrees Fahrenheit.
     */
    public static final String TEMP_F = "TEMP_F";

    /**
     * Amphere - Electric current.
     */
    public static final String OTH_A = "OTH_A";

    /**
     * Candela - Luminosity (intensity of light).
     */
    public static final String OTH_cd = "OTH_cd";

    /**
     * Mole - Substance (molecule).
     */
    public static final String OTH_mol = "OTH_mol";

    /**
     * Each.
     */
    public static final String OTH_ea = "OTH_ea";

    /**
     * Per Person.
     */
    public static final String OTH_pp = "OTH_pp";

    /**
     * Box.
     */
    public static final String OTH_box = "OTH_box";

    /**
     * Package.
     */
    public static final String OTH_pk = "OTH_pk";

}

