// <autogenerated>
//   This file was generated by T4 code generator GenerateBoundedContextDomain.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

<?php

namespace Dddml\Wms\Domain;

class DocumentAction
{

		
    const DRAFT = 'Draft';

		
    const COMPLETE = 'Complete';

		
    const VOID = 'Void';

		
    const CLOSE = 'Close';

		
    const REVERSE = 'Reverse';

}

