DROP view if exists `AttributeValue_RV` ;
DROP view if exists `AttributeUse_RV` ;
DROP view if exists `InOutLine_RV` ;
DROP view if exists `InventoryItemEntry_RV` ;
DROP view if exists `InventoryItemRequirementEntry_RV` ;
DROP view if exists `OrderItem_RV` ;
DROP view if exists `SellableInventoryItemEntry_RV` ;
DROP view if exists `ShipmentItem_RV` ;
DROP view if exists `AttributeSetInstanceExtensionField_RV` ;
