
    create table ContactMeches (
        ContactMechId VARCHAR(20) not null,
       Version BIGINT not null,
       ContactMechTypeId VARCHAR(20),
       InfoString VARCHAR(255),
       ToName VARCHAR(100),
       AttnName VARCHAR(100),
       Address1 VARCHAR(255),
       Address2 VARCHAR(255),
       Directions VARCHAR(255),
       City VARCHAR(100),
       PostalCode VARCHAR(60),
       PostalCodeExt VARCHAR(60),
       CountryGeoId VARCHAR(20),
       StateProvinceGeoId VARCHAR(20),
       CountyGeoId VARCHAR(20),
       PostalCodeGeoId VARCHAR(20),
       GeoPointId VARCHAR(20),
       CountryCode VARCHAR(10),
       AreaCode VARCHAR(10),
       ContactNumber VARCHAR(60),
       AskForName VARCHAR(100),
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (ContactMechId)
    );
    create table ContactMechStateEvents (
        ContactMechId VARCHAR(20) not null,
       Version BIGINT not null,
       StateEventType VARCHAR(255) not null,
       ContactMechTypeId VARCHAR(20),
       InfoString VARCHAR(255),
       ToName VARCHAR(100),
       AttnName VARCHAR(100),
       Address1 VARCHAR(255),
       Address2 VARCHAR(255),
       Directions VARCHAR(255),
       City VARCHAR(100),
       PostalCode VARCHAR(60),
       PostalCodeExt VARCHAR(60),
       CountryGeoId VARCHAR(20),
       StateProvinceGeoId VARCHAR(20),
       CountyGeoId VARCHAR(20),
       PostalCodeGeoId VARCHAR(20),
       GeoPointId VARCHAR(20),
       CountryCode VARCHAR(10),
       AreaCode VARCHAR(10),
       ContactNumber VARCHAR(60),
       AskForName VARCHAR(100),
       Active TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyContactMechTypeIdRemoved TINYINT(1),
       IsPropertyInfoStringRemoved TINYINT(1),
       IsPropertyToNameRemoved TINYINT(1),
       IsPropertyAttnNameRemoved TINYINT(1),
       IsPropertyAddress1Removed TINYINT(1),
       IsPropertyAddress2Removed TINYINT(1),
       IsPropertyDirectionsRemoved TINYINT(1),
       IsPropertyCityRemoved TINYINT(1),
       IsPropertyPostalCodeRemoved TINYINT(1),
       IsPropertyPostalCodeExtRemoved TINYINT(1),
       IsPropertyCountryGeoIdRemoved TINYINT(1),
       IsPropertyStateProvinceGeoIdRemoved TINYINT(1),
       IsPropertyCountyGeoIdRemoved TINYINT(1),
       IsPropertyPostalCodeGeoIdRemoved TINYINT(1),
       IsPropertyGeoPointIdRemoved TINYINT(1),
       IsPropertyCountryCodeRemoved TINYINT(1),
       IsPropertyAreaCodeRemoved TINYINT(1),
       IsPropertyContactNumberRemoved TINYINT(1),
       IsPropertyAskForNameRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       primary key (ContactMechId, Version)
    );
    create table Facilities (
        FacilityId VARCHAR(20) not null,
       Version BIGINT not null,
       FacilityTypeId VARCHAR(20),
       ParentFacilityId VARCHAR(20),
       OwnerPartyId VARCHAR(20),
       DefaultInventoryItemTypeId VARCHAR(20),
       FacilityName VARCHAR(100),
       PrimaryFacilityGroupId VARCHAR(20),
       OldSquareFootage DECIMAL(20,0),
       FacilitySize DECIMAL(18,6),
       FacilitySizeUomId VARCHAR(20),
       ProductStoreId VARCHAR(20),
       DefaultDaysToShip DECIMAL(20,0),
       OpenedDate DATETIME,
       ClosedDate DATETIME,
       Description VARCHAR(255),
       DefaultDimensionUomId VARCHAR(20),
       DefaultWeightUomId VARCHAR(20),
       GeoPointId VARCHAR(20),
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (FacilityId)
    );
    create table FacilityStateEvents (
        FacilityId VARCHAR(20) not null,
       Version BIGINT not null,
       StateEventType VARCHAR(255) not null,
       FacilityTypeId VARCHAR(20),
       ParentFacilityId VARCHAR(20),
       OwnerPartyId VARCHAR(20),
       DefaultInventoryItemTypeId VARCHAR(20),
       FacilityName VARCHAR(100),
       PrimaryFacilityGroupId VARCHAR(20),
       OldSquareFootage DECIMAL(20,0),
       FacilitySize DECIMAL(18,6),
       FacilitySizeUomId VARCHAR(20),
       ProductStoreId VARCHAR(20),
       DefaultDaysToShip DECIMAL(20,0),
       OpenedDate DATETIME,
       ClosedDate DATETIME,
       Description VARCHAR(255),
       DefaultDimensionUomId VARCHAR(20),
       DefaultWeightUomId VARCHAR(20),
       GeoPointId VARCHAR(20),
       Active TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyFacilityTypeIdRemoved TINYINT(1),
       IsPropertyParentFacilityIdRemoved TINYINT(1),
       IsPropertyOwnerPartyIdRemoved TINYINT(1),
       IsPropertyDefaultInventoryItemTypeIdRemoved TINYINT(1),
       IsPropertyFacilityNameRemoved TINYINT(1),
       IsPropertyPrimaryFacilityGroupIdRemoved TINYINT(1),
       IsPropertyOldSquareFootageRemoved TINYINT(1),
       IsPropertyFacilitySizeRemoved TINYINT(1),
       IsPropertyFacilitySizeUomIdRemoved TINYINT(1),
       IsPropertyProductStoreIdRemoved TINYINT(1),
       IsPropertyDefaultDaysToShipRemoved TINYINT(1),
       IsPropertyOpenedDateRemoved TINYINT(1),
       IsPropertyClosedDateRemoved TINYINT(1),
       IsPropertyDescriptionRemoved TINYINT(1),
       IsPropertyDefaultDimensionUomIdRemoved TINYINT(1),
       IsPropertyDefaultWeightUomIdRemoved TINYINT(1),
       IsPropertyGeoPointIdRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       primary key (FacilityId, Version)
    );
    create table AttributeValue_RV (
        AttributeValueIdAttributeId VARCHAR(50) not null,
       AttributeValueIdValue VARCHAR(50) not null,
       AttributeVersion BIGINT not null,
       AttributeValueName VARCHAR(255),
       Description VARCHAR(255),
       ReferenceId VARCHAR(255),
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       AttributeAttributeName VARCHAR(255),
       AttributeOrganizationId VARCHAR(255),
       AttributeDescription VARCHAR(255),
       AttributeIsMandatory TINYINT(1),
       AttributeAttributeValueType VARCHAR(255),
       AttributeAttributeValueLength INTEGER,
       AttributeIsList TINYINT(1),
       AttributeFieldName VARCHAR(255),
       AttributeReferenceId VARCHAR(255),
       AttributeCreatedBy VARCHAR(255),
       AttributeCreatedAt DATETIME,
       AttributeUpdatedBy VARCHAR(255),
       AttributeUpdatedAt DATETIME,
       AttributeActive TINYINT(1),
       AttributeDeleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (AttributeValueIdAttributeId, AttributeValueIdValue)
    );
    create table AttributeAlias_RV (
        AttributeAliasIdAttributeId VARCHAR(50) not null,
       AttributeAliasIdCode VARCHAR(50) not null,
       AttributeVersion BIGINT not null,
       Name VARCHAR(255),
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       AttributeAttributeName VARCHAR(255),
       AttributeOrganizationId VARCHAR(255),
       AttributeDescription VARCHAR(255),
       AttributeIsMandatory TINYINT(1),
       AttributeAttributeValueType VARCHAR(255),
       AttributeAttributeValueLength INTEGER,
       AttributeIsList TINYINT(1),
       AttributeFieldName VARCHAR(255),
       AttributeReferenceId VARCHAR(255),
       AttributeCreatedBy VARCHAR(255),
       AttributeCreatedAt DATETIME,
       AttributeUpdatedBy VARCHAR(255),
       AttributeUpdatedAt DATETIME,
       AttributeActive TINYINT(1),
       AttributeDeleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (AttributeAliasIdAttributeId, AttributeAliasIdCode),
      unique (AttributeAliasIdCode),
      unique (Name)
    );
    create table AttributeUse_RV (
        AttributeSetAttributeUseIdAttributeSetId VARCHAR(50) not null,
       AttributeSetAttributeUseIdAttributeId VARCHAR(50) not null,
       AttributeSetVersion BIGINT not null,
       SequenceNumber INTEGER,
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       AttributeSetAttributeSetName VARCHAR(255),
       AttributeSetOrganizationId VARCHAR(255),
       AttributeSetDescription VARCHAR(255),
       AttributeSetReferenceId VARCHAR(255),
       AttributeSetIsInstanceAttributeSet TINYINT(1),
       AttributeSetIsMandatory TINYINT(1),
       AttributeSetCreatedBy VARCHAR(255),
       AttributeSetCreatedAt DATETIME,
       AttributeSetUpdatedBy VARCHAR(255),
       AttributeSetUpdatedAt DATETIME,
       AttributeSetActive TINYINT(1),
       AttributeSetDeleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (AttributeSetAttributeUseIdAttributeSetId, AttributeSetAttributeUseIdAttributeId)
    );
    alter table PhysicalInventoryLines 
        add column LineNumber VARCHAR(50);
    alter table PhysicalInventoryLineStateEvents 
        add column LineNumber VARCHAR(50);
    alter table PhysicalInventoryLineStateEvents 
        add column IsPropertyLineNumberRemoved TINYINT(1);
    create table OrderRoles (
        OrderRoleIdOrderId VARCHAR(20) not null,
       OrderRoleIdPartyRoleIdPartyId VARCHAR(20) not null,
       OrderRoleIdPartyRoleIdRoleTypeId VARCHAR(20) not null,
       Version BIGINT not null,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (OrderRoleIdOrderId, OrderRoleIdPartyRoleIdPartyId, OrderRoleIdPartyRoleIdRoleTypeId)
    );
    create table OrderRoleStateEvents (
        OrderRoleIdOrderId VARCHAR(20) not null,
       OrderRoleIdPartyRoleIdPartyId VARCHAR(20) not null,
       OrderRoleIdPartyRoleIdRoleTypeId VARCHAR(20) not null,
       OrderVersion BIGINT not null,
       StateEventType VARCHAR(255) not null,
       Active TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       Version BIGINT not null,
       IsPropertyActiveRemoved TINYINT(1),
       primary key (OrderRoleIdOrderId, OrderRoleIdPartyRoleIdPartyId, OrderRoleIdPartyRoleIdRoleTypeId, OrderVersion)
    );
    create table OrderShipGroups (
        OrderShipGroupIdOrderId VARCHAR(20) not null,
       OrderShipGroupIdShipGroupSeqId DECIMAL(20,0) not null,
       Version BIGINT not null,
       ShipmentMethodTypeId VARCHAR(20),
       SupplierPartyId VARCHAR(20),
       VendorPartyId VARCHAR(20),
       CarrierPartyId VARCHAR(20),
       CarrierRoleTypeId VARCHAR(20),
       FacilityId VARCHAR(20),
       ContactMechId VARCHAR(20),
       TelecomContactMechId VARCHAR(20),
       TrackingNumber VARCHAR(60),
       ShippingInstructions VARCHAR(255),
       MaySplit CHAR(1),
       GiftMessage VARCHAR(255),
       IsGift CHAR(1),
       ShipAfterDate DATETIME,
       ShipByDate DATETIME,
       EstimatedShipDate DATETIME,
       EstimatedDeliveryDate DATETIME,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (OrderShipGroupIdOrderId, OrderShipGroupIdShipGroupSeqId)
    );
    create table OrderShipGroupStateEvents (
        OrderShipGroupIdOrderId VARCHAR(20) not null,
       OrderShipGroupIdShipGroupSeqId DECIMAL(20,0) not null,
       OrderVersion BIGINT not null,
       StateEventType VARCHAR(255) not null,
       ShipmentMethodTypeId VARCHAR(20),
       SupplierPartyId VARCHAR(20),
       VendorPartyId VARCHAR(20),
       CarrierPartyId VARCHAR(20),
       CarrierRoleTypeId VARCHAR(20),
       FacilityId VARCHAR(20),
       ContactMechId VARCHAR(20),
       TelecomContactMechId VARCHAR(20),
       TrackingNumber VARCHAR(60),
       ShippingInstructions VARCHAR(255),
       MaySplit CHAR(1),
       GiftMessage VARCHAR(255),
       IsGift CHAR(1),
       ShipAfterDate DATETIME,
       ShipByDate DATETIME,
       EstimatedShipDate DATETIME,
       EstimatedDeliveryDate DATETIME,
       Active TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       Version BIGINT not null,
       IsPropertyShipmentMethodTypeIdRemoved TINYINT(1),
       IsPropertySupplierPartyIdRemoved TINYINT(1),
       IsPropertyVendorPartyIdRemoved TINYINT(1),
       IsPropertyCarrierPartyIdRemoved TINYINT(1),
       IsPropertyCarrierRoleTypeIdRemoved TINYINT(1),
       IsPropertyFacilityIdRemoved TINYINT(1),
       IsPropertyContactMechIdRemoved TINYINT(1),
       IsPropertyTelecomContactMechIdRemoved TINYINT(1),
       IsPropertyTrackingNumberRemoved TINYINT(1),
       IsPropertyShippingInstructionsRemoved TINYINT(1),
       IsPropertyMaySplitRemoved TINYINT(1),
       IsPropertyGiftMessageRemoved TINYINT(1),
       IsPropertyIsGiftRemoved TINYINT(1),
       IsPropertyShipAfterDateRemoved TINYINT(1),
       IsPropertyShipByDateRemoved TINYINT(1),
       IsPropertyEstimatedShipDateRemoved TINYINT(1),
       IsPropertyEstimatedDeliveryDateRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       primary key (OrderShipGroupIdOrderId, OrderShipGroupIdShipGroupSeqId, OrderVersion)
    );
    create table PartyRoles (
        PartyRoleIdPartyId VARCHAR(20) not null,
       PartyRoleIdRoleTypeId VARCHAR(20) not null,
       Version BIGINT not null,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (PartyRoleIdPartyId, PartyRoleIdRoleTypeId)
    );
    create table PartyRoleStateEvents (
        PartyRoleIdPartyId VARCHAR(20) not null,
       PartyRoleIdRoleTypeId VARCHAR(20) not null,
       Version BIGINT not null,
       StateEventType VARCHAR(255) not null,
       Active TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyActiveRemoved TINYINT(1),
       primary key (PartyRoleIdPartyId, PartyRoleIdRoleTypeId, Version)
    );
    create table Picklists (
        PicklistId VARCHAR(20) not null,
       Version BIGINT not null,
       Description VARCHAR(255),
       FacilityId VARCHAR(20),
       ShipmentMethodTypeId VARCHAR(20),
       StatusId VARCHAR(20),
       PicklistDate DATETIME,
       CreatedByUserLogin VARCHAR(250),
       LastModifiedByUserLogin VARCHAR(250),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (PicklistId)
    );
    create table PicklistStateEvents (
        PicklistId VARCHAR(20) not null,
       Version BIGINT not null,
       StateEventType VARCHAR(255) not null,
       Description VARCHAR(255),
       FacilityId VARCHAR(20),
       ShipmentMethodTypeId VARCHAR(20),
       StatusId VARCHAR(20),
       PicklistDate DATETIME,
       Active TINYINT(1),
       CreatedByUserLogin VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyDescriptionRemoved TINYINT(1),
       IsPropertyFacilityIdRemoved TINYINT(1),
       IsPropertyShipmentMethodTypeIdRemoved TINYINT(1),
       IsPropertyStatusIdRemoved TINYINT(1),
       IsPropertyPicklistDateRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       primary key (PicklistId, Version)
    );
    create table PicklistRoles (
        PicklistRoleIdPicklistId VARCHAR(20) not null,
       PicklistRoleIdPartyRoleIdPartyId VARCHAR(20) not null,
       PicklistRoleIdPartyRoleIdRoleTypeId VARCHAR(20) not null,
       Version BIGINT not null,
       CreatedByUserLogin VARCHAR(250),
       LastModifiedByUserLogin VARCHAR(250),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (PicklistRoleIdPicklistId, PicklistRoleIdPartyRoleIdPartyId, PicklistRoleIdPartyRoleIdRoleTypeId)
    );
    create table PicklistRoleStateEvents (
        PicklistRoleIdPicklistId VARCHAR(20) not null,
       PicklistRoleIdPartyRoleIdPartyId VARCHAR(20) not null,
       PicklistRoleIdPartyRoleIdRoleTypeId VARCHAR(20) not null,
       PicklistVersion BIGINT not null,
       StateEventType VARCHAR(255) not null,
       Active TINYINT(1),
       CreatedByUserLogin VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       Version BIGINT not null,
       IsPropertyActiveRemoved TINYINT(1),
       primary key (PicklistRoleIdPicklistId, PicklistRoleIdPartyRoleIdPartyId, PicklistRoleIdPartyRoleIdRoleTypeId, PicklistVersion)
    );
    create table PicklistBins (
        PicklistBinId VARCHAR(20) not null,
       Version BIGINT not null,
       PicklistId VARCHAR(20),
       BinLocationNumber DECIMAL(20,0),
       PrimaryOrderId VARCHAR(20),
       PrimaryShipGroupSeqId DECIMAL(20,0),
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (PicklistBinId)
    );
    create table PicklistBinStateEvents (
        PicklistBinId VARCHAR(20) not null,
       Version BIGINT not null,
       StateEventType VARCHAR(255) not null,
       PicklistId VARCHAR(20),
       BinLocationNumber DECIMAL(20,0),
       PrimaryOrderId VARCHAR(20),
       PrimaryShipGroupSeqId DECIMAL(20,0),
       Active TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyPicklistIdRemoved TINYINT(1),
       IsPropertyBinLocationNumberRemoved TINYINT(1),
       IsPropertyPrimaryOrderIdRemoved TINYINT(1),
       IsPropertyPrimaryShipGroupSeqIdRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       primary key (PicklistBinId, Version)
    );
    create table PicklistItems (
        PicklistBinId VARCHAR(20) not null,
       OrderId VARCHAR(20) not null,
       OrderItemSeqId VARCHAR(20) not null,
       ShipGroupSeqId DECIMAL(20,0) not null,
       ProductId VARCHAR(60) not null,
       LocatorId VARCHAR(50) not null,
       AttributeSetInstanceId VARCHAR(50) not null,
       Version BIGINT not null,
       ItemStatusId VARCHAR(20),
       Quantity DECIMAL(18,6),
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (PicklistBinId, OrderId, OrderItemSeqId, ShipGroupSeqId, ProductId, LocatorId, AttributeSetInstanceId)
    );
    create table PicklistItemStateEvents (
        PicklistBinId VARCHAR(20) not null,
       OrderId VARCHAR(20) not null,
       OrderItemSeqId VARCHAR(20) not null,
       ShipGroupSeqId DECIMAL(20,0) not null,
       ProductId VARCHAR(60) not null,
       LocatorId VARCHAR(50) not null,
       AttributeSetInstanceId VARCHAR(50) not null,
       PicklistBinVersion BIGINT not null,
       StateEventType VARCHAR(255) not null,
       ItemStatusId VARCHAR(20),
       Quantity DECIMAL(18,6),
       Active TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       Version BIGINT not null,
       IsPropertyItemStatusIdRemoved TINYINT(1),
       IsPropertyQuantityRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       primary key (PicklistBinId, OrderId, OrderItemSeqId, ShipGroupSeqId, ProductId, LocatorId, AttributeSetInstanceId, PicklistBinVersion)
    );
    create table RoleTypes (
        RoleTypeId VARCHAR(20) not null,
       Version BIGINT not null,
       ParentTypeId VARCHAR(20),
       HasTable CHAR(1),
       Description VARCHAR(255),
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (RoleTypeId)
    );
    create table RoleTypeStateEvents (
        RoleTypeId VARCHAR(20) not null,
       Version BIGINT not null,
       StateEventType VARCHAR(255) not null,
       ParentTypeId VARCHAR(20),
       HasTable CHAR(1),
       Description VARCHAR(255),
       Active TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyParentTypeIdRemoved TINYINT(1),
       IsPropertyHasTableRemoved TINYINT(1),
       IsPropertyDescriptionRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       primary key (RoleTypeId, Version)
    );
    alter table Shipments 
        add column PrimaryShipGroupSeqId DECIMAL(20,0);
    alter table ShipmentStateEvents 
        add column PrimaryShipGroupSeqId DECIMAL(20,0);
    alter table ShipmentStateEvents 
        add column IsPropertyPrimaryShipGroupSeqIdRemoved TINYINT(1);
    alter table ShipmentReceipts 
        add column LocatorId VARCHAR(255);
    alter table ShipmentReceipts 
        add column ShipmentPackageSeqId VARCHAR(20);
    alter table ShipmentReceipts 
        add column OrderId VARCHAR(20);
    alter table ShipmentReceipts 
        add column OrderItemSeqId VARCHAR(20);
    alter table ShipmentReceipts 
        add column ReturnId VARCHAR(20);
    alter table ShipmentReceipts 
        add column ReturnItemSeqId VARCHAR(20);
    alter table ShipmentReceiptStateEvents 
        add column LocatorId VARCHAR(255);
    alter table ShipmentReceiptStateEvents 
        add column ShipmentPackageSeqId VARCHAR(20);
    alter table ShipmentReceiptStateEvents 
        add column OrderId VARCHAR(20);
    alter table ShipmentReceiptStateEvents 
        add column OrderItemSeqId VARCHAR(20);
    alter table ShipmentReceiptStateEvents 
        add column ReturnId VARCHAR(20);
    alter table ShipmentReceiptStateEvents 
        add column ReturnItemSeqId VARCHAR(20);
    alter table ShipmentReceiptStateEvents 
        add column IsPropertyLocatorIdRemoved TINYINT(1);
    alter table ShipmentReceiptStateEvents 
        add column IsPropertyShipmentPackageSeqIdRemoved TINYINT(1);
    alter table ShipmentReceiptStateEvents 
        add column IsPropertyOrderIdRemoved TINYINT(1);
    alter table ShipmentReceiptStateEvents 
        add column IsPropertyOrderItemSeqIdRemoved TINYINT(1);
    alter table ShipmentReceiptStateEvents 
        add column IsPropertyReturnIdRemoved TINYINT(1);
    alter table ShipmentReceiptStateEvents 
        add column IsPropertyReturnItemSeqIdRemoved TINYINT(1);
    create table ItemIssuances (
        ShipmentItemIssuanceIdShipmentId VARCHAR(20) not null,
       ShipmentItemIssuanceIdItemIssuanceSeqId VARCHAR(20) not null,
       Version BIGINT not null,
       OrderId VARCHAR(20),
       OrderItemSeqId VARCHAR(20),
       ShipGroupSeqId DECIMAL(20,0),
       ProductId VARCHAR(60),
       LocatorId VARCHAR(50),
       AttributeSetInstanceId VARCHAR(50),
       ShipmentItemSeqId VARCHAR(20),
       FixedAssetId VARCHAR(20),
       MaintHistSeqId VARCHAR(20),
       IssuedDateTime DATETIME,
       IssuedByUserLoginId VARCHAR(250),
       Quantity DECIMAL(18,6),
       CancelQuantity DECIMAL(18,6),
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (ShipmentItemIssuanceIdShipmentId, ShipmentItemIssuanceIdItemIssuanceSeqId)
    );
    create table ItemIssuanceStateEvents (
        ShipmentItemIssuanceIdShipmentId VARCHAR(20) not null,
       ShipmentItemIssuanceIdItemIssuanceSeqId VARCHAR(20) not null,
       ShipmentVersion BIGINT not null,
       StateEventType VARCHAR(255) not null,
       OrderId VARCHAR(20),
       OrderItemSeqId VARCHAR(20),
       ShipGroupSeqId DECIMAL(20,0),
       ProductId VARCHAR(60),
       LocatorId VARCHAR(50),
       AttributeSetInstanceId VARCHAR(50),
       ShipmentItemSeqId VARCHAR(20),
       FixedAssetId VARCHAR(20),
       MaintHistSeqId VARCHAR(20),
       IssuedDateTime DATETIME,
       IssuedByUserLoginId VARCHAR(250),
       Quantity DECIMAL(18,6),
       CancelQuantity DECIMAL(18,6),
       Active TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       Version BIGINT not null,
       IsPropertyOrderIdRemoved TINYINT(1),
       IsPropertyOrderItemSeqIdRemoved TINYINT(1),
       IsPropertyShipGroupSeqIdRemoved TINYINT(1),
       IsPropertyProductIdRemoved TINYINT(1),
       IsPropertyLocatorIdRemoved TINYINT(1),
       IsPropertyAttributeSetInstanceIdRemoved TINYINT(1),
       IsPropertyShipmentItemSeqIdRemoved TINYINT(1),
       IsPropertyFixedAssetIdRemoved TINYINT(1),
       IsPropertyMaintHistSeqIdRemoved TINYINT(1),
       IsPropertyIssuedDateTimeRemoved TINYINT(1),
       IsPropertyIssuedByUserLoginIdRemoved TINYINT(1),
       IsPropertyQuantityRemoved TINYINT(1),
       IsPropertyCancelQuantityRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       primary key (ShipmentItemIssuanceIdShipmentId, ShipmentItemIssuanceIdItemIssuanceSeqId, ShipmentVersion)
    );
    create table ShipmentMethodTypes (
        ShipmentMethodTypeId VARCHAR(20) not null,
       Version BIGINT not null,
       Description VARCHAR(255),
       SequenceNum DECIMAL(20,0),
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (ShipmentMethodTypeId)
    );
    create table ShipmentMethodTypeStateEvents (
        ShipmentMethodTypeId VARCHAR(20) not null,
       Version BIGINT not null,
       StateEventType VARCHAR(255) not null,
       Description VARCHAR(255),
       SequenceNum DECIMAL(20,0),
       Active TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyDescriptionRemoved TINYINT(1),
       IsPropertySequenceNumRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       primary key (ShipmentMethodTypeId, Version)
    );
    create table ShipmentPackages (
        ShipmentPackageIdShipmentId VARCHAR(20) not null,
       ShipmentPackageIdShipmentPackageSeqId VARCHAR(20) not null,
       Version BIGINT not null,
       ShipmentBoxTypeId VARCHAR(20),
       DateCreated DATETIME,
       BoxLength DECIMAL(18,6),
       BoxHeight DECIMAL(18,6),
       BoxWidth DECIMAL(18,6),
       DimensionUomId VARCHAR(20),
       Weight DECIMAL(18,6),
       WeightUomId VARCHAR(20),
       InsuredValue DECIMAL(18,2),
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (ShipmentPackageIdShipmentId, ShipmentPackageIdShipmentPackageSeqId)
    );
    create table ShipmentPackageStateEvents (
        ShipmentPackageIdShipmentId VARCHAR(20) not null,
       ShipmentPackageIdShipmentPackageSeqId VARCHAR(20) not null,
       Version BIGINT not null,
       StateEventType VARCHAR(255) not null,
       ShipmentBoxTypeId VARCHAR(20),
       DateCreated DATETIME,
       BoxLength DECIMAL(18,6),
       BoxHeight DECIMAL(18,6),
       BoxWidth DECIMAL(18,6),
       DimensionUomId VARCHAR(20),
       Weight DECIMAL(18,6),
       WeightUomId VARCHAR(20),
       InsuredValue DECIMAL(18,2),
       Active TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyShipmentBoxTypeIdRemoved TINYINT(1),
       IsPropertyDateCreatedRemoved TINYINT(1),
       IsPropertyBoxLengthRemoved TINYINT(1),
       IsPropertyBoxHeightRemoved TINYINT(1),
       IsPropertyBoxWidthRemoved TINYINT(1),
       IsPropertyDimensionUomIdRemoved TINYINT(1),
       IsPropertyWeightRemoved TINYINT(1),
       IsPropertyWeightUomIdRemoved TINYINT(1),
       IsPropertyInsuredValueRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       primary key (ShipmentPackageIdShipmentId, ShipmentPackageIdShipmentPackageSeqId, Version)
    );
    create table ShipmentPackageContents (
        ShipmentPackageContentIdShipmentPackageIdShipmentId VARCHAR(20) not null,
       ShipmentPackageContentIdShipmentPackageIdShipmentPackageSeqId VARCHAR(20) not null,
       ShipmentPackageContentIdShipmentItemSeqId VARCHAR(20) not null,
       Version BIGINT not null,
       Quantity DECIMAL(18,6),
       SubProductId VARCHAR(20),
       SubProductQuantity DECIMAL(18,6),
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (ShipmentPackageContentIdShipmentPackageIdShipmentId, ShipmentPackageContentIdShipmentPackageIdShipmentPackageSeqId, ShipmentPackageContentIdShipmentItemSeqId)
    );
    create table ShipmentPackageContentStateEvents (
        ShipmentPackageContentIdShipmentPackageIdShipmentId VARCHAR(20) not null,
       ShipmentPackageContentIdShipmentPackageIdShipmentPackageSeqId VARCHAR(20) not null,
       ShipmentPackageContentIdShipmentItemSeqId VARCHAR(20) not null,
       ShipmentPackageVersion BIGINT not null,
       StateEventType VARCHAR(255) not null,
       Quantity DECIMAL(18,6),
       SubProductId VARCHAR(20),
       SubProductQuantity DECIMAL(18,6),
       Active TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       Version BIGINT not null,
       IsPropertyQuantityRemoved TINYINT(1),
       IsPropertySubProductIdRemoved TINYINT(1),
       IsPropertySubProductQuantityRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       primary key (ShipmentPackageContentIdShipmentPackageIdShipmentId, ShipmentPackageContentIdShipmentPackageIdShipmentPackageSeqId, ShipmentPackageContentIdShipmentItemSeqId, ShipmentPackageVersion)
    );
    create table InOutLine_RV (
        InOutLineIdInOutDocumentNumber VARCHAR(50) not null,
       InOutLineIdLineNumber VARCHAR(50) not null,
       InOutVersion BIGINT not null,
       LocatorId VARCHAR(255),
       ProductId VARCHAR(60),
       AttributeSetInstanceId VARCHAR(255),
       Description VARCHAR(255),
       QuantityUomId VARCHAR(255),
       MovementQuantity NUMERIC(19,5),
       PickedQuantity NUMERIC(19,5),
       IsInvoiced TINYINT(1),
       Processed TINYINT(1),
       RmaLineNumber VARCHAR(255),
       ReversalLineNumber VARCHAR(255),
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       InOutDocumentStatusId VARCHAR(255),
       InOutPosted TINYINT(1),
       InOutProcessed TINYINT(1),
       InOutProcessing VARCHAR(255),
       InOutDocumentTypeId VARCHAR(255),
       InOutDescription VARCHAR(255),
       InOutOrderId VARCHAR(255),
       InOutDateOrdered DATETIME,
       InOutIsPrinted TINYINT(1),
       InOutMovementTypeId VARCHAR(255),
       InOutMovementDate DATETIME,
       InOutBusinessPartnerId VARCHAR(255),
       InOutWarehouseId VARCHAR(255),
       InOutPOReference VARCHAR(255),
       InOutFreightAmount NUMERIC(19,5),
       InOutShipperId VARCHAR(255),
       InOutChargeAmount NUMERIC(19,5),
       InOutDatePrinted DATETIME,
       InOutCreatedFrom VARCHAR(255),
       InOutSalesRepresentativeId VARCHAR(255),
       InOutNumberOfPackages INTEGER,
       InOutPickDate DATETIME,
       InOutShipDate DATETIME,
       InOutTrackingNumber VARCHAR(255),
       InOutDateReceived DATETIME,
       InOutIsInTransit TINYINT(1),
       InOutIsApproved TINYINT(1),
       InOutIsInDispute TINYINT(1),
       InOutRmaDocumentNumber VARCHAR(255),
       InOutReversalDocumentNumber VARCHAR(255),
       InOutCreatedBy VARCHAR(255),
       InOutCreatedAt DATETIME,
       InOutUpdatedBy VARCHAR(255),
       InOutUpdatedAt DATETIME,
       InOutActive TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (InOutLineIdInOutDocumentNumber, InOutLineIdLineNumber)
    );
    create table InventoryItemEntry_RV (
        ProductId VARCHAR(60) not null,
       LocatorId VARCHAR(50) not null,
       AttributeSetInstanceId VARCHAR(50) not null,
       EntrySeqId BIGINT not null,
       InventoryItemVersion BIGINT not null,
       OnHandQuantity NUMERIC(19,5),
       InTransitQuantity NUMERIC(19,5),
       ReservedQuantity NUMERIC(19,5),
       OccupiedQuantity NUMERIC(19,5),
       VirtualQuantity NUMERIC(19,5),
       SourceDocumentTypeId VARCHAR(255) not null,
       SourceDocumentNumber VARCHAR(255) not null,
       SourceLineNumber VARCHAR(255),
       SourceLineSeqId INTEGER,
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       InventoryItemOnHandQuantity NUMERIC(19,5),
       InventoryItemInTransitQuantity NUMERIC(19,5),
       InventoryItemReservedQuantity NUMERIC(19,5),
       InventoryItemOccupiedQuantity NUMERIC(19,5),
       InventoryItemVirtualQuantity NUMERIC(19,5),
       InventoryItemCreatedBy VARCHAR(255),
       InventoryItemCreatedAt DATETIME,
       InventoryItemUpdatedBy VARCHAR(255),
       InventoryItemUpdatedAt DATETIME,
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (ProductId, LocatorId, AttributeSetInstanceId, EntrySeqId),
      unique (SourceDocumentTypeId, SourceDocumentNumber, SourceLineNumber, SourceLineSeqId)
    );
    create table InventoryItemRequirementEntry_RV (
        ProductId VARCHAR(60) not null,
       LocatorId VARCHAR(50) not null,
       AttributeSetInstanceId VARCHAR(50) not null,
       EntrySeqId BIGINT not null,
       InventoryItemRequirementVersion BIGINT not null,
       Quantity NUMERIC(19,5),
       SrcEventProductId VARCHAR(60),
       SrcEventLocatorId VARCHAR(50),
       SrcEventAttributeSetInstanceId VARCHAR(50),
       SrcEventEntrySeqId BIGINT,
       SrcEventInventoryPostingRuleId VARCHAR(50),
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       InventoryItemRequirementQuantity NUMERIC(19,5),
       InventoryItemRequirementCreatedBy VARCHAR(255),
       InventoryItemRequirementCreatedAt DATETIME,
       InventoryItemRequirementUpdatedBy VARCHAR(255),
       InventoryItemRequirementUpdatedAt DATETIME,
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (ProductId, LocatorId, AttributeSetInstanceId, EntrySeqId),
      unique (SrcEventProductId, SrcEventLocatorId, SrcEventAttributeSetInstanceId, SrcEventEntrySeqId, SrcEventInventoryPostingRuleId)
    );
    create table MovementLine_RV (
        MovementLineIdMovementDocumentNumber VARCHAR(50) not null,
       MovementLineIdLineNumber VARCHAR(50) not null,
       MovementVersion BIGINT not null,
       MovementQuantity NUMERIC(19,5),
       ProductId VARCHAR(60),
       LocatorIdFrom VARCHAR(255),
       LocatorIdTo VARCHAR(255),
       AttributeSetInstanceId VARCHAR(255),
       Processed TINYINT(1),
       ReversalLineNumber VARCHAR(255),
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       MovementDocumentStatusId VARCHAR(255),
       MovementMovementDate DATETIME,
       MovementPosted TINYINT(1),
       MovementProcessed TINYINT(1),
       MovementProcessing VARCHAR(255),
       MovementDateReceived DATETIME,
       MovementDocumentTypeId VARCHAR(255),
       MovementIsInTransit TINYINT(1),
       MovementIsApproved TINYINT(1),
       MovementApprovalAmount NUMERIC(19,5),
       MovementShipperId VARCHAR(255),
       MovementSalesRepresentativeId VARCHAR(255),
       MovementBusinessPartnerId VARCHAR(255),
       MovementChargeAmount NUMERIC(19,5),
       MovementCreateFrom VARCHAR(255),
       MovementFreightAmount NUMERIC(19,5),
       MovementReversalDocumentNumber VARCHAR(255),
       MovementWarehouseIdFrom VARCHAR(255),
       MovementWarehouseIdTo VARCHAR(255),
       MovementDescription VARCHAR(255),
       MovementCreatedBy VARCHAR(255),
       MovementCreatedAt DATETIME,
       MovementUpdatedBy VARCHAR(255),
       MovementUpdatedAt DATETIME,
       MovementActive TINYINT(1),
       MovementDeleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (MovementLineIdMovementDocumentNumber, MovementLineIdLineNumber)
    );
    create table MovementConfirmationLine_RV (
        MovementConfirmationLineIdMovementConfirmationDocumentNumber VARCHAR(50) not null,
       MovementConfirmationLineIdLineNumber VARCHAR(50) not null,
       MovementConfirmationVersion BIGINT not null,
       MovementLineNumber VARCHAR(255),
       TargetQuantity NUMERIC(19,5),
       ConfirmedQuantity NUMERIC(19,5),
       DifferenceQuantity NUMERIC(19,5),
       ScrappedQuantity NUMERIC(19,5),
       Description VARCHAR(255),
       Processed TINYINT(1),
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       MovementConfirmationDocumentStatusId VARCHAR(255),
       MovementConfirmationMovementDocumentNumber VARCHAR(255),
       MovementConfirmationIsApproved TINYINT(1),
       MovementConfirmationApprovalAmount NUMERIC(19,5),
       MovementConfirmationProcessed TINYINT(1),
       MovementConfirmationProcessing VARCHAR(255),
       MovementConfirmationDocumentTypeId VARCHAR(255),
       MovementConfirmationDescription VARCHAR(255),
       MovementConfirmationCreatedBy VARCHAR(255),
       MovementConfirmationCreatedAt DATETIME,
       MovementConfirmationUpdatedBy VARCHAR(255),
       MovementConfirmationUpdatedAt DATETIME,
       MovementConfirmationActive TINYINT(1),
       MovementConfirmationDeleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (MovementConfirmationLineIdMovementConfirmationDocumentNumber, MovementConfirmationLineIdLineNumber)
    );
    create table OrderRole_RV (
        OrderRoleIdOrderId VARCHAR(20) not null,
       OrderRoleIdPartyRoleIdPartyId VARCHAR(20) not null,
       OrderRoleIdPartyRoleIdRoleTypeId VARCHAR(20) not null,
       OrderVersion BIGINT not null,
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       OrderOrderTypeId VARCHAR(20),
       OrderOrderName VARCHAR(100),
       OrderExternalId VARCHAR(20),
       OrderSalesChannelEnumId VARCHAR(20),
       OrderOrderDate DATETIME,
       OrderPriority CHAR(1),
       OrderEntryDate DATETIME,
       OrderPickSheetPrintedDate DATETIME,
       OrderStatusId VARCHAR(20),
       OrderCurrencyUom VARCHAR(20),
       OrderSyncStatusId VARCHAR(20),
       OrderBillingAccountId VARCHAR(20),
       OrderOriginFacilityId VARCHAR(20),
       OrderWebSiteId VARCHAR(20),
       OrderProductStoreId VARCHAR(20),
       OrderTerminalId VARCHAR(60),
       OrderTransactionId VARCHAR(60),
       OrderAutoOrderShoppingListId VARCHAR(20),
       OrderNeedsInventoryIssuance CHAR(1),
       OrderIsRushOrder CHAR(1),
       OrderInternalCode VARCHAR(60),
       OrderRemainingSubTotal DECIMAL(18,2),
       OrderGrandTotal DECIMAL(18,2),
       OrderInvoicePerShipment CHAR(1),
       OrderCreatedBy VARCHAR(255),
       OrderCreatedAt DATETIME,
       OrderUpdatedBy VARCHAR(255),
       OrderUpdatedAt DATETIME,
       OrderActive TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (OrderRoleIdOrderId, OrderRoleIdPartyRoleIdPartyId, OrderRoleIdPartyRoleIdRoleTypeId)
    );
    create table OrderRoleMvoStateEvents (
        OrderRoleIdOrderId VARCHAR(20) not null,
       OrderRoleIdPartyRoleIdPartyId VARCHAR(20) not null,
       OrderRoleIdPartyRoleIdRoleTypeId VARCHAR(20) not null,
       OrderVersion BIGINT not null,
       StateEventType VARCHAR(255) not null,
       Version BIGINT,
       Active TINYINT(1),
       OrderOrderTypeId VARCHAR(20),
       OrderOrderName VARCHAR(100),
       OrderExternalId VARCHAR(20),
       OrderSalesChannelEnumId VARCHAR(20),
       OrderOrderDate DATETIME,
       OrderPriority CHAR(1),
       OrderEntryDate DATETIME,
       OrderPickSheetPrintedDate DATETIME,
       OrderStatusId VARCHAR(20),
       OrderCurrencyUom VARCHAR(20),
       OrderSyncStatusId VARCHAR(20),
       OrderBillingAccountId VARCHAR(20),
       OrderOriginFacilityId VARCHAR(20),
       OrderWebSiteId VARCHAR(20),
       OrderProductStoreId VARCHAR(20),
       OrderTerminalId VARCHAR(60),
       OrderTransactionId VARCHAR(60),
       OrderAutoOrderShoppingListId VARCHAR(20),
       OrderNeedsInventoryIssuance CHAR(1),
       OrderIsRushOrder CHAR(1),
       OrderInternalCode VARCHAR(60),
       OrderRemainingSubTotal DECIMAL(18,2),
       OrderGrandTotal DECIMAL(18,2),
       OrderInvoicePerShipment CHAR(1),
       OrderCreatedBy VARCHAR(255),
       OrderCreatedAt DATETIME,
       OrderUpdatedBy VARCHAR(255),
       OrderUpdatedAt DATETIME,
       OrderActive TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyVersionRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       IsPropertyOrderOrderTypeIdRemoved TINYINT(1),
       IsPropertyOrderOrderNameRemoved TINYINT(1),
       IsPropertyOrderExternalIdRemoved TINYINT(1),
       IsPropertyOrderSalesChannelEnumIdRemoved TINYINT(1),
       IsPropertyOrderOrderDateRemoved TINYINT(1),
       IsPropertyOrderPriorityRemoved TINYINT(1),
       IsPropertyOrderEntryDateRemoved TINYINT(1),
       IsPropertyOrderPickSheetPrintedDateRemoved TINYINT(1),
       IsPropertyOrderStatusIdRemoved TINYINT(1),
       IsPropertyOrderCurrencyUomRemoved TINYINT(1),
       IsPropertyOrderSyncStatusIdRemoved TINYINT(1),
       IsPropertyOrderBillingAccountIdRemoved TINYINT(1),
       IsPropertyOrderOriginFacilityIdRemoved TINYINT(1),
       IsPropertyOrderWebSiteIdRemoved TINYINT(1),
       IsPropertyOrderProductStoreIdRemoved TINYINT(1),
       IsPropertyOrderTerminalIdRemoved TINYINT(1),
       IsPropertyOrderTransactionIdRemoved TINYINT(1),
       IsPropertyOrderAutoOrderShoppingListIdRemoved TINYINT(1),
       IsPropertyOrderNeedsInventoryIssuanceRemoved TINYINT(1),
       IsPropertyOrderIsRushOrderRemoved TINYINT(1),
       IsPropertyOrderInternalCodeRemoved TINYINT(1),
       IsPropertyOrderRemainingSubTotalRemoved TINYINT(1),
       IsPropertyOrderGrandTotalRemoved TINYINT(1),
       IsPropertyOrderInvoicePerShipmentRemoved TINYINT(1),
       IsPropertyOrderCreatedByRemoved TINYINT(1),
       IsPropertyOrderCreatedAtRemoved TINYINT(1),
       IsPropertyOrderUpdatedByRemoved TINYINT(1),
       IsPropertyOrderUpdatedAtRemoved TINYINT(1),
       IsPropertyOrderActiveRemoved TINYINT(1),
       primary key (OrderRoleIdOrderId, OrderRoleIdPartyRoleIdPartyId, OrderRoleIdPartyRoleIdRoleTypeId, OrderVersion)
    );
    create table OrderItem_RV (
        OrderItemIdOrderId VARCHAR(20) not null,
       OrderItemIdOrderItemSeqId VARCHAR(20) not null,
       OrderVersion BIGINT not null,
       ProductId VARCHAR(60),
       ExternalProductId VARCHAR(60),
       Quantity DECIMAL(18,6),
       CancelQuantity DECIMAL(18,6),
       SelectedAmount DECIMAL(18,6),
       ExternalId VARCHAR(20),
       OrderItemTypeId VARCHAR(20),
       OrderItemGroupSeqId VARCHAR(20),
       IsItemGroupPrimary CHAR(1),
       FromInventoryItemId VARCHAR(20),
       IsPromo CHAR(1),
       QuoteId VARCHAR(20),
       QuoteItemSeqId VARCHAR(20),
       ShoppingListId VARCHAR(20),
       ShoppingListItemSeqId VARCHAR(20),
       UnitPrice DECIMAL(18,3),
       UnitListPrice DECIMAL(18,3),
       UnitAverageCost DECIMAL(18,2),
       UnitRecurringPrice DECIMAL(18,2),
       IsModifiedPrice CHAR(1),
       RecurringFreqUomId VARCHAR(20),
       ItemDescription VARCHAR(255),
       Comments VARCHAR(255),
       CorrespondingPoId VARCHAR(20),
       StatusId VARCHAR(20),
       SyncStatusId VARCHAR(20),
       EstimatedShipDate DATETIME,
       EstimatedDeliveryDate DATETIME,
       AutoCancelDate DATETIME,
       DontCancelSetDate DATETIME,
       DontCancelSetBy VARCHAR(250),
       ShipBeforeDate DATETIME,
       ShipAfterDate DATETIME,
       CancelBackOrderDate DATETIME,
       OverrideGlAccountId VARCHAR(20),
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       OrderOrderTypeId VARCHAR(20),
       OrderOrderName VARCHAR(100),
       OrderExternalId VARCHAR(20),
       OrderSalesChannelEnumId VARCHAR(20),
       OrderOrderDate DATETIME,
       OrderPriority CHAR(1),
       OrderEntryDate DATETIME,
       OrderPickSheetPrintedDate DATETIME,
       OrderStatusId VARCHAR(20),
       OrderCurrencyUom VARCHAR(20),
       OrderSyncStatusId VARCHAR(20),
       OrderBillingAccountId VARCHAR(20),
       OrderOriginFacilityId VARCHAR(20),
       OrderWebSiteId VARCHAR(20),
       OrderProductStoreId VARCHAR(20),
       OrderTerminalId VARCHAR(60),
       OrderTransactionId VARCHAR(60),
       OrderAutoOrderShoppingListId VARCHAR(20),
       OrderNeedsInventoryIssuance CHAR(1),
       OrderIsRushOrder CHAR(1),
       OrderInternalCode VARCHAR(60),
       OrderRemainingSubTotal DECIMAL(18,2),
       OrderGrandTotal DECIMAL(18,2),
       OrderInvoicePerShipment CHAR(1),
       OrderCreatedBy VARCHAR(255),
       OrderCreatedAt DATETIME,
       OrderUpdatedBy VARCHAR(255),
       OrderUpdatedAt DATETIME,
       OrderActive TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (OrderItemIdOrderId, OrderItemIdOrderItemSeqId)
    );
    create table OrderShipGroup_RV (
        OrderShipGroupIdOrderId VARCHAR(20) not null,
       OrderShipGroupIdShipGroupSeqId DECIMAL(20,0) not null,
       OrderVersion BIGINT not null,
       ShipmentMethodTypeId VARCHAR(20),
       SupplierPartyId VARCHAR(20),
       VendorPartyId VARCHAR(20),
       CarrierPartyId VARCHAR(20),
       CarrierRoleTypeId VARCHAR(20),
       FacilityId VARCHAR(20),
       ContactMechId VARCHAR(20),
       TelecomContactMechId VARCHAR(20),
       TrackingNumber VARCHAR(60),
       ShippingInstructions VARCHAR(255),
       MaySplit CHAR(1),
       GiftMessage VARCHAR(255),
       IsGift CHAR(1),
       ShipAfterDate DATETIME,
       ShipByDate DATETIME,
       EstimatedShipDate DATETIME,
       EstimatedDeliveryDate DATETIME,
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       OrderOrderTypeId VARCHAR(20),
       OrderOrderName VARCHAR(100),
       OrderExternalId VARCHAR(20),
       OrderSalesChannelEnumId VARCHAR(20),
       OrderOrderDate DATETIME,
       OrderPriority CHAR(1),
       OrderEntryDate DATETIME,
       OrderPickSheetPrintedDate DATETIME,
       OrderStatusId VARCHAR(20),
       OrderCurrencyUom VARCHAR(20),
       OrderSyncStatusId VARCHAR(20),
       OrderBillingAccountId VARCHAR(20),
       OrderOriginFacilityId VARCHAR(20),
       OrderWebSiteId VARCHAR(20),
       OrderProductStoreId VARCHAR(20),
       OrderTerminalId VARCHAR(60),
       OrderTransactionId VARCHAR(60),
       OrderAutoOrderShoppingListId VARCHAR(20),
       OrderNeedsInventoryIssuance CHAR(1),
       OrderIsRushOrder CHAR(1),
       OrderInternalCode VARCHAR(60),
       OrderRemainingSubTotal DECIMAL(18,2),
       OrderGrandTotal DECIMAL(18,2),
       OrderInvoicePerShipment CHAR(1),
       OrderCreatedBy VARCHAR(255),
       OrderCreatedAt DATETIME,
       OrderUpdatedBy VARCHAR(255),
       OrderUpdatedAt DATETIME,
       OrderActive TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (OrderShipGroupIdOrderId, OrderShipGroupIdShipGroupSeqId)
    );
    create table OrderShipGroupMvoStateEvents (
        OrderShipGroupIdOrderId VARCHAR(20) not null,
       OrderShipGroupIdShipGroupSeqId DECIMAL(20,0) not null,
       OrderVersion BIGINT not null,
       StateEventType VARCHAR(255) not null,
       ShipmentMethodTypeId VARCHAR(20),
       SupplierPartyId VARCHAR(20),
       VendorPartyId VARCHAR(20),
       CarrierPartyId VARCHAR(20),
       CarrierRoleTypeId VARCHAR(20),
       FacilityId VARCHAR(20),
       ContactMechId VARCHAR(20),
       TelecomContactMechId VARCHAR(20),
       TrackingNumber VARCHAR(60),
       ShippingInstructions VARCHAR(255),
       MaySplit CHAR(1),
       GiftMessage VARCHAR(255),
       IsGift CHAR(1),
       ShipAfterDate DATETIME,
       ShipByDate DATETIME,
       EstimatedShipDate DATETIME,
       EstimatedDeliveryDate DATETIME,
       Version BIGINT,
       Active TINYINT(1),
       OrderOrderTypeId VARCHAR(20),
       OrderOrderName VARCHAR(100),
       OrderExternalId VARCHAR(20),
       OrderSalesChannelEnumId VARCHAR(20),
       OrderOrderDate DATETIME,
       OrderPriority CHAR(1),
       OrderEntryDate DATETIME,
       OrderPickSheetPrintedDate DATETIME,
       OrderStatusId VARCHAR(20),
       OrderCurrencyUom VARCHAR(20),
       OrderSyncStatusId VARCHAR(20),
       OrderBillingAccountId VARCHAR(20),
       OrderOriginFacilityId VARCHAR(20),
       OrderWebSiteId VARCHAR(20),
       OrderProductStoreId VARCHAR(20),
       OrderTerminalId VARCHAR(60),
       OrderTransactionId VARCHAR(60),
       OrderAutoOrderShoppingListId VARCHAR(20),
       OrderNeedsInventoryIssuance CHAR(1),
       OrderIsRushOrder CHAR(1),
       OrderInternalCode VARCHAR(60),
       OrderRemainingSubTotal DECIMAL(18,2),
       OrderGrandTotal DECIMAL(18,2),
       OrderInvoicePerShipment CHAR(1),
       OrderCreatedBy VARCHAR(255),
       OrderCreatedAt DATETIME,
       OrderUpdatedBy VARCHAR(255),
       OrderUpdatedAt DATETIME,
       OrderActive TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyShipmentMethodTypeIdRemoved TINYINT(1),
       IsPropertySupplierPartyIdRemoved TINYINT(1),
       IsPropertyVendorPartyIdRemoved TINYINT(1),
       IsPropertyCarrierPartyIdRemoved TINYINT(1),
       IsPropertyCarrierRoleTypeIdRemoved TINYINT(1),
       IsPropertyFacilityIdRemoved TINYINT(1),
       IsPropertyContactMechIdRemoved TINYINT(1),
       IsPropertyTelecomContactMechIdRemoved TINYINT(1),
       IsPropertyTrackingNumberRemoved TINYINT(1),
       IsPropertyShippingInstructionsRemoved TINYINT(1),
       IsPropertyMaySplitRemoved TINYINT(1),
       IsPropertyGiftMessageRemoved TINYINT(1),
       IsPropertyIsGiftRemoved TINYINT(1),
       IsPropertyShipAfterDateRemoved TINYINT(1),
       IsPropertyShipByDateRemoved TINYINT(1),
       IsPropertyEstimatedShipDateRemoved TINYINT(1),
       IsPropertyEstimatedDeliveryDateRemoved TINYINT(1),
       IsPropertyVersionRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       IsPropertyOrderOrderTypeIdRemoved TINYINT(1),
       IsPropertyOrderOrderNameRemoved TINYINT(1),
       IsPropertyOrderExternalIdRemoved TINYINT(1),
       IsPropertyOrderSalesChannelEnumIdRemoved TINYINT(1),
       IsPropertyOrderOrderDateRemoved TINYINT(1),
       IsPropertyOrderPriorityRemoved TINYINT(1),
       IsPropertyOrderEntryDateRemoved TINYINT(1),
       IsPropertyOrderPickSheetPrintedDateRemoved TINYINT(1),
       IsPropertyOrderStatusIdRemoved TINYINT(1),
       IsPropertyOrderCurrencyUomRemoved TINYINT(1),
       IsPropertyOrderSyncStatusIdRemoved TINYINT(1),
       IsPropertyOrderBillingAccountIdRemoved TINYINT(1),
       IsPropertyOrderOriginFacilityIdRemoved TINYINT(1),
       IsPropertyOrderWebSiteIdRemoved TINYINT(1),
       IsPropertyOrderProductStoreIdRemoved TINYINT(1),
       IsPropertyOrderTerminalIdRemoved TINYINT(1),
       IsPropertyOrderTransactionIdRemoved TINYINT(1),
       IsPropertyOrderAutoOrderShoppingListIdRemoved TINYINT(1),
       IsPropertyOrderNeedsInventoryIssuanceRemoved TINYINT(1),
       IsPropertyOrderIsRushOrderRemoved TINYINT(1),
       IsPropertyOrderInternalCodeRemoved TINYINT(1),
       IsPropertyOrderRemainingSubTotalRemoved TINYINT(1),
       IsPropertyOrderGrandTotalRemoved TINYINT(1),
       IsPropertyOrderInvoicePerShipmentRemoved TINYINT(1),
       IsPropertyOrderCreatedByRemoved TINYINT(1),
       IsPropertyOrderCreatedAtRemoved TINYINT(1),
       IsPropertyOrderUpdatedByRemoved TINYINT(1),
       IsPropertyOrderUpdatedAtRemoved TINYINT(1),
       IsPropertyOrderActiveRemoved TINYINT(1),
       primary key (OrderShipGroupIdOrderId, OrderShipGroupIdShipGroupSeqId, OrderVersion)
    );
    create table PhysicalInventoryLine_RV (
        PhysicalInventoryLineIdPhysicalInventoryDocumentNumber VARCHAR(50) not null,
       ProductId VARCHAR(60) not null,
       LocatorId VARCHAR(50) not null,
       AttributeSetInstanceId VARCHAR(50) not null,
       PhysicalInventoryVersion BIGINT not null,
       BookQuantity NUMERIC(19,5),
       CountedQuantity NUMERIC(19,5),
       Processed TINYINT(1),
       LineNumber VARCHAR(50) not null,
       ReversalLineNumber BIGINT,
       Description VARCHAR(255),
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Deleted TINYINT(1),
       PhysicalInventoryDocumentStatusId VARCHAR(255),
       PhysicalInventoryWarehouseId VARCHAR(255),
       PhysicalInventoryLocatorIdPattern VARCHAR(255),
       PhysicalInventoryProductIdPattern VARCHAR(60),
       PhysicalInventoryPosted TINYINT(1),
       PhysicalInventoryProcessed TINYINT(1),
       PhysicalInventoryProcessing VARCHAR(255),
       PhysicalInventoryDocumentTypeId VARCHAR(255),
       PhysicalInventoryMovementDate DATETIME,
       PhysicalInventoryDescription VARCHAR(255),
       PhysicalInventoryIsApproved TINYINT(1),
       PhysicalInventoryApprovalAmount NUMERIC(19,5),
       PhysicalInventoryIsQuantityUpdated TINYINT(1),
       PhysicalInventoryReversalDocumentNumber VARCHAR(255),
       PhysicalInventoryCreatedBy VARCHAR(255),
       PhysicalInventoryCreatedAt DATETIME,
       PhysicalInventoryUpdatedBy VARCHAR(255),
       PhysicalInventoryUpdatedAt DATETIME,
       PhysicalInventoryActive TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (PhysicalInventoryLineIdPhysicalInventoryDocumentNumber, ProductId, LocatorId, AttributeSetInstanceId),
      unique (LineNumber)
    );
    alter table PhysicalInventoryLineMvoStateEvents 
        add column LineNumber VARCHAR(50);
    alter table PhysicalInventoryLineMvoStateEvents 
        add column IsPropertyLineNumberRemoved TINYINT(1);
    create table PicklistRole_RV (
        PicklistRoleIdPicklistId VARCHAR(20) not null,
       PicklistRoleIdPartyRoleIdPartyId VARCHAR(20) not null,
       PicklistRoleIdPartyRoleIdRoleTypeId VARCHAR(20) not null,
       PicklistVersion BIGINT not null,
       CreatedByUserLogin VARCHAR(250),
       LastModifiedByUserLogin VARCHAR(250),
       Version BIGINT,
       Active TINYINT(1),
       Deleted TINYINT(1),
       PicklistDescription VARCHAR(255),
       PicklistFacilityId VARCHAR(20),
       PicklistShipmentMethodTypeId VARCHAR(20),
       PicklistStatusId VARCHAR(20),
       PicklistPicklistDate DATETIME,
       PicklistCreatedByUserLogin VARCHAR(250),
       PicklistLastModifiedByUserLogin VARCHAR(250),
       PicklistCreatedAt DATETIME,
       PicklistUpdatedAt DATETIME,
       PicklistActive TINYINT(1),
       PicklistDeleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (PicklistRoleIdPicklistId, PicklistRoleIdPartyRoleIdPartyId, PicklistRoleIdPartyRoleIdRoleTypeId)
    );
    create table PicklistRoleMvoStateEvents (
        PicklistRoleIdPicklistId VARCHAR(20) not null,
       PicklistRoleIdPartyRoleIdPartyId VARCHAR(20) not null,
       PicklistRoleIdPartyRoleIdRoleTypeId VARCHAR(20) not null,
       PicklistVersion BIGINT not null,
       StateEventType VARCHAR(255) not null,
       Version BIGINT,
       Active TINYINT(1),
       PicklistDescription VARCHAR(255),
       PicklistFacilityId VARCHAR(20),
       PicklistShipmentMethodTypeId VARCHAR(20),
       PicklistStatusId VARCHAR(20),
       PicklistPicklistDate DATETIME,
       PicklistCreatedByUserLogin VARCHAR(250),
       PicklistLastModifiedByUserLogin VARCHAR(250),
       PicklistCreatedAt DATETIME,
       PicklistUpdatedAt DATETIME,
       PicklistActive TINYINT(1),
       PicklistDeleted TINYINT(1),
       CreatedByUserLogin VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyVersionRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       IsPropertyPicklistDescriptionRemoved TINYINT(1),
       IsPropertyPicklistFacilityIdRemoved TINYINT(1),
       IsPropertyPicklistShipmentMethodTypeIdRemoved TINYINT(1),
       IsPropertyPicklistStatusIdRemoved TINYINT(1),
       IsPropertyPicklistPicklistDateRemoved TINYINT(1),
       IsPropertyPicklistCreatedByUserLoginRemoved TINYINT(1),
       IsPropertyPicklistLastModifiedByUserLoginRemoved TINYINT(1),
       IsPropertyPicklistCreatedAtRemoved TINYINT(1),
       IsPropertyPicklistUpdatedAtRemoved TINYINT(1),
       IsPropertyPicklistActiveRemoved TINYINT(1),
       IsPropertyPicklistDeletedRemoved TINYINT(1),
       primary key (PicklistRoleIdPicklistId, PicklistRoleIdPartyRoleIdPartyId, PicklistRoleIdPartyRoleIdRoleTypeId, PicklistVersion)
    );
    create table PicklistItem_RV (
        PicklistBinId VARCHAR(20) not null,
       OrderId VARCHAR(20) not null,
       OrderItemSeqId VARCHAR(20) not null,
       ShipGroupSeqId DECIMAL(20,0) not null,
       ProductId VARCHAR(60) not null,
       LocatorId VARCHAR(50) not null,
       AttributeSetInstanceId VARCHAR(50) not null,
       PicklistBinVersion BIGINT not null,
       ItemStatusId VARCHAR(20),
       Quantity DECIMAL(18,6),
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       PicklistBinPicklistId VARCHAR(20),
       PicklistBinBinLocationNumber DECIMAL(20,0),
       PicklistBinPrimaryOrderId VARCHAR(20),
       PicklistBinPrimaryShipGroupSeqId DECIMAL(20,0),
       PicklistBinCreatedBy VARCHAR(255),
       PicklistBinCreatedAt DATETIME,
       PicklistBinUpdatedBy VARCHAR(255),
       PicklistBinUpdatedAt DATETIME,
       PicklistBinActive TINYINT(1),
       PicklistBinDeleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (PicklistBinId, OrderId, OrderItemSeqId, ShipGroupSeqId, ProductId, LocatorId, AttributeSetInstanceId)
    );
    create table PicklistItemMvoStateEvents (
        PicklistBinId VARCHAR(20) not null,
       OrderId VARCHAR(20) not null,
       OrderItemSeqId VARCHAR(20) not null,
       ShipGroupSeqId DECIMAL(20,0) not null,
       ProductId VARCHAR(60) not null,
       LocatorId VARCHAR(50) not null,
       AttributeSetInstanceId VARCHAR(50) not null,
       PicklistBinVersion BIGINT not null,
       StateEventType VARCHAR(255) not null,
       ItemStatusId VARCHAR(20),
       Quantity DECIMAL(18,6),
       Version BIGINT,
       Active TINYINT(1),
       PicklistBinPicklistId VARCHAR(20),
       PicklistBinBinLocationNumber DECIMAL(20,0),
       PicklistBinPrimaryOrderId VARCHAR(20),
       PicklistBinPrimaryShipGroupSeqId DECIMAL(20,0),
       PicklistBinCreatedBy VARCHAR(255),
       PicklistBinCreatedAt DATETIME,
       PicklistBinUpdatedBy VARCHAR(255),
       PicklistBinUpdatedAt DATETIME,
       PicklistBinActive TINYINT(1),
       PicklistBinDeleted TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyItemStatusIdRemoved TINYINT(1),
       IsPropertyQuantityRemoved TINYINT(1),
       IsPropertyVersionRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       IsPropertyPicklistBinPicklistIdRemoved TINYINT(1),
       IsPropertyPicklistBinBinLocationNumberRemoved TINYINT(1),
       IsPropertyPicklistBinPrimaryOrderIdRemoved TINYINT(1),
       IsPropertyPicklistBinPrimaryShipGroupSeqIdRemoved TINYINT(1),
       IsPropertyPicklistBinCreatedByRemoved TINYINT(1),
       IsPropertyPicklistBinCreatedAtRemoved TINYINT(1),
       IsPropertyPicklistBinUpdatedByRemoved TINYINT(1),
       IsPropertyPicklistBinUpdatedAtRemoved TINYINT(1),
       IsPropertyPicklistBinActiveRemoved TINYINT(1),
       IsPropertyPicklistBinDeletedRemoved TINYINT(1),
       primary key (PicklistBinId, OrderId, OrderItemSeqId, ShipGroupSeqId, ProductId, LocatorId, AttributeSetInstanceId, PicklistBinVersion)
    );
    create table SellableInventoryItemEntry_RV (
        ProductId VARCHAR(60) not null,
       LocatorId VARCHAR(50) not null,
       AttributeSetInstanceId VARCHAR(50) not null,
       EntrySeqId BIGINT not null,
       SellableInventoryItemVersion BIGINT not null,
       SellableQuantity NUMERIC(19,5),
       SrcEventProductId VARCHAR(60),
       SrcEventLocatorId VARCHAR(50),
       SrcEventAttributeSetInstanceId VARCHAR(50),
       SrcEventEntrySeqId BIGINT,
       SrcEventInventoryPostingRuleId VARCHAR(50),
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       SellableInventoryItemSellableQuantity NUMERIC(19,5),
       SellableInventoryItemCreatedBy VARCHAR(255),
       SellableInventoryItemCreatedAt DATETIME,
       SellableInventoryItemUpdatedBy VARCHAR(255),
       SellableInventoryItemUpdatedAt DATETIME,
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (ProductId, LocatorId, AttributeSetInstanceId, EntrySeqId),
      unique (SrcEventProductId, SrcEventLocatorId, SrcEventAttributeSetInstanceId, SrcEventEntrySeqId, SrcEventInventoryPostingRuleId)
    );
    create table ShipmentItem_RV (
        ShipmentItemIdShipmentId VARCHAR(20) not null,
       ShipmentItemIdShipmentItemSeqId VARCHAR(20) not null,
       ShipmentVersion BIGINT not null,
       ProductId VARCHAR(60),
       AttributeSetInstanceId VARCHAR(255),
       Quantity DECIMAL(18,6) not null,
       ShipmentContentDescription VARCHAR(255),
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       ShipmentShipmentTypeId VARCHAR(20),
       ShipmentStatusId VARCHAR(20),
       ShipmentPrimaryOrderId VARCHAR(20),
       ShipmentPrimaryReturnId VARCHAR(20),
       ShipmentPrimaryShipGroupSeqId DECIMAL(20,0),
       ShipmentPicklistBinId VARCHAR(20),
       ShipmentEstimatedReadyDate DATETIME,
       ShipmentEstimatedShipDate DATETIME,
       ShipmentEstimatedShipWorkEffId VARCHAR(20),
       ShipmentEstimatedArrivalDate DATETIME,
       ShipmentEstimatedArrivalWorkEffId VARCHAR(20),
       ShipmentLatestCancelDate DATETIME,
       ShipmentEstimatedShipCost DECIMAL(18,2),
       ShipmentCurrencyUomId VARCHAR(20),
       ShipmentHandlingInstructions VARCHAR(255),
       ShipmentOriginFacilityId VARCHAR(20),
       ShipmentDestinationFacilityId VARCHAR(20),
       ShipmentOriginContactMechId VARCHAR(20),
       ShipmentOriginTelecomNumberId VARCHAR(20),
       ShipmentDestinationContactMechId VARCHAR(20),
       ShipmentDestinationTelecomNumberId VARCHAR(20),
       ShipmentPartyIdTo VARCHAR(20),
       ShipmentPartyIdFrom VARCHAR(20),
       ShipmentAdditionalShippingCharge DECIMAL(18,2),
       ShipmentAddtlShippingChargeDesc VARCHAR(255),
       ShipmentCreatedBy VARCHAR(255),
       ShipmentCreatedAt DATETIME,
       ShipmentUpdatedBy VARCHAR(255),
       ShipmentUpdatedAt DATETIME,
       ShipmentActive TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (ShipmentItemIdShipmentId, ShipmentItemIdShipmentItemSeqId)
    );
    alter table ShipmentItemMvoStateEvents 
        add column ShipmentPrimaryShipGroupSeqId DECIMAL(20,0);
    alter table ShipmentItemMvoStateEvents 
        add column IsPropertyShipmentPrimaryShipGroupSeqIdRemoved TINYINT(1);
    create table ShipmentReceipt_RV (
        ShipmentReceiptIdShipmentId VARCHAR(20) not null,
       ShipmentReceiptIdReceiptSeqId VARCHAR(20) not null,
       ShipmentVersion BIGINT not null,
       ProductId VARCHAR(60),
       AttributeSetInstanceId VARCHAR(255),
       LocatorId VARCHAR(255),
       ShipmentItemSeqId VARCHAR(20),
       ShipmentPackageSeqId VARCHAR(20),
       OrderId VARCHAR(20),
       OrderItemSeqId VARCHAR(20),
       ReturnId VARCHAR(20),
       ReturnItemSeqId VARCHAR(20),
       RejectionReasonId VARCHAR(60),
       DamageStatusId VARCHAR(20),
       DamageReasonId VARCHAR(60),
       ReceivedBy VARCHAR(250),
       DatetimeReceived DATETIME,
       ItemDescription VARCHAR(255),
       AcceptedQuantity DECIMAL(18,6) not null,
       RejectedQuantity DECIMAL(18,6) not null,
       DamagedQuantity DECIMAL(18,6) not null,
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       ShipmentShipmentTypeId VARCHAR(20),
       ShipmentStatusId VARCHAR(20),
       ShipmentPrimaryOrderId VARCHAR(20),
       ShipmentPrimaryReturnId VARCHAR(20),
       ShipmentPrimaryShipGroupSeqId DECIMAL(20,0),
       ShipmentPicklistBinId VARCHAR(20),
       ShipmentEstimatedReadyDate DATETIME,
       ShipmentEstimatedShipDate DATETIME,
       ShipmentEstimatedShipWorkEffId VARCHAR(20),
       ShipmentEstimatedArrivalDate DATETIME,
       ShipmentEstimatedArrivalWorkEffId VARCHAR(20),
       ShipmentLatestCancelDate DATETIME,
       ShipmentEstimatedShipCost DECIMAL(18,2),
       ShipmentCurrencyUomId VARCHAR(20),
       ShipmentHandlingInstructions VARCHAR(255),
       ShipmentOriginFacilityId VARCHAR(20),
       ShipmentDestinationFacilityId VARCHAR(20),
       ShipmentOriginContactMechId VARCHAR(20),
       ShipmentOriginTelecomNumberId VARCHAR(20),
       ShipmentDestinationContactMechId VARCHAR(20),
       ShipmentDestinationTelecomNumberId VARCHAR(20),
       ShipmentPartyIdTo VARCHAR(20),
       ShipmentPartyIdFrom VARCHAR(20),
       ShipmentAdditionalShippingCharge DECIMAL(18,2),
       ShipmentAddtlShippingChargeDesc VARCHAR(255),
       ShipmentCreatedBy VARCHAR(255),
       ShipmentCreatedAt DATETIME,
       ShipmentUpdatedBy VARCHAR(255),
       ShipmentUpdatedAt DATETIME,
       ShipmentActive TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (ShipmentReceiptIdShipmentId, ShipmentReceiptIdReceiptSeqId)
    );
    alter table ShipmentReceiptMvoStateEvents 
        add column LocatorId VARCHAR(255);
    alter table ShipmentReceiptMvoStateEvents 
        add column ShipmentPackageSeqId VARCHAR(20);
    alter table ShipmentReceiptMvoStateEvents 
        add column OrderId VARCHAR(20);
    alter table ShipmentReceiptMvoStateEvents 
        add column OrderItemSeqId VARCHAR(20);
    alter table ShipmentReceiptMvoStateEvents 
        add column ReturnId VARCHAR(20);
    alter table ShipmentReceiptMvoStateEvents 
        add column ReturnItemSeqId VARCHAR(20);
    alter table ShipmentReceiptMvoStateEvents 
        add column ShipmentPrimaryShipGroupSeqId DECIMAL(20,0);
    alter table ShipmentReceiptMvoStateEvents 
        add column IsPropertyLocatorIdRemoved TINYINT(1);
    alter table ShipmentReceiptMvoStateEvents 
        add column IsPropertyShipmentPackageSeqIdRemoved TINYINT(1);
    alter table ShipmentReceiptMvoStateEvents 
        add column IsPropertyOrderIdRemoved TINYINT(1);
    alter table ShipmentReceiptMvoStateEvents 
        add column IsPropertyOrderItemSeqIdRemoved TINYINT(1);
    alter table ShipmentReceiptMvoStateEvents 
        add column IsPropertyReturnIdRemoved TINYINT(1);
    alter table ShipmentReceiptMvoStateEvents 
        add column IsPropertyReturnItemSeqIdRemoved TINYINT(1);
    alter table ShipmentReceiptMvoStateEvents 
        add column IsPropertyShipmentPrimaryShipGroupSeqIdRemoved TINYINT(1);
    create table ItemIssuance_RV (
        ShipmentItemIssuanceIdShipmentId VARCHAR(20) not null,
       ShipmentItemIssuanceIdItemIssuanceSeqId VARCHAR(20) not null,
       ShipmentVersion BIGINT not null,
       OrderId VARCHAR(20),
       OrderItemSeqId VARCHAR(20),
       ShipGroupSeqId DECIMAL(20,0),
       ProductId VARCHAR(60),
       LocatorId VARCHAR(50),
       AttributeSetInstanceId VARCHAR(50),
       ShipmentItemSeqId VARCHAR(20),
       FixedAssetId VARCHAR(20),
       MaintHistSeqId VARCHAR(20),
       IssuedDateTime DATETIME,
       IssuedByUserLoginId VARCHAR(250),
       Quantity DECIMAL(18,6),
       CancelQuantity DECIMAL(18,6),
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       ShipmentShipmentTypeId VARCHAR(20),
       ShipmentStatusId VARCHAR(20),
       ShipmentPrimaryOrderId VARCHAR(20),
       ShipmentPrimaryReturnId VARCHAR(20),
       ShipmentPrimaryShipGroupSeqId DECIMAL(20,0),
       ShipmentPicklistBinId VARCHAR(20),
       ShipmentEstimatedReadyDate DATETIME,
       ShipmentEstimatedShipDate DATETIME,
       ShipmentEstimatedShipWorkEffId VARCHAR(20),
       ShipmentEstimatedArrivalDate DATETIME,
       ShipmentEstimatedArrivalWorkEffId VARCHAR(20),
       ShipmentLatestCancelDate DATETIME,
       ShipmentEstimatedShipCost DECIMAL(18,2),
       ShipmentCurrencyUomId VARCHAR(20),
       ShipmentHandlingInstructions VARCHAR(255),
       ShipmentOriginFacilityId VARCHAR(20),
       ShipmentDestinationFacilityId VARCHAR(20),
       ShipmentOriginContactMechId VARCHAR(20),
       ShipmentOriginTelecomNumberId VARCHAR(20),
       ShipmentDestinationContactMechId VARCHAR(20),
       ShipmentDestinationTelecomNumberId VARCHAR(20),
       ShipmentPartyIdTo VARCHAR(20),
       ShipmentPartyIdFrom VARCHAR(20),
       ShipmentAdditionalShippingCharge DECIMAL(18,2),
       ShipmentAddtlShippingChargeDesc VARCHAR(255),
       ShipmentCreatedBy VARCHAR(255),
       ShipmentCreatedAt DATETIME,
       ShipmentUpdatedBy VARCHAR(255),
       ShipmentUpdatedAt DATETIME,
       ShipmentActive TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (ShipmentItemIssuanceIdShipmentId, ShipmentItemIssuanceIdItemIssuanceSeqId)
    );
    create table ItemIssuanceMvoStateEvents (
        ShipmentItemIssuanceIdShipmentId VARCHAR(20) not null,
       ShipmentItemIssuanceIdItemIssuanceSeqId VARCHAR(20) not null,
       ShipmentVersion BIGINT not null,
       StateEventType VARCHAR(255) not null,
       OrderId VARCHAR(20),
       OrderItemSeqId VARCHAR(20),
       ShipGroupSeqId DECIMAL(20,0),
       ProductId VARCHAR(60),
       LocatorId VARCHAR(50),
       AttributeSetInstanceId VARCHAR(50),
       ShipmentItemSeqId VARCHAR(20),
       FixedAssetId VARCHAR(20),
       MaintHistSeqId VARCHAR(20),
       IssuedDateTime DATETIME,
       IssuedByUserLoginId VARCHAR(250),
       Quantity DECIMAL(18,6),
       CancelQuantity DECIMAL(18,6),
       Version BIGINT,
       Active TINYINT(1),
       ShipmentShipmentTypeId VARCHAR(20),
       ShipmentStatusId VARCHAR(20),
       ShipmentPrimaryOrderId VARCHAR(20),
       ShipmentPrimaryReturnId VARCHAR(20),
       ShipmentPrimaryShipGroupSeqId DECIMAL(20,0),
       ShipmentPicklistBinId VARCHAR(20),
       ShipmentEstimatedReadyDate DATETIME,
       ShipmentEstimatedShipDate DATETIME,
       ShipmentEstimatedShipWorkEffId VARCHAR(20),
       ShipmentEstimatedArrivalDate DATETIME,
       ShipmentEstimatedArrivalWorkEffId VARCHAR(20),
       ShipmentLatestCancelDate DATETIME,
       ShipmentEstimatedShipCost DECIMAL(18,2),
       ShipmentCurrencyUomId VARCHAR(20),
       ShipmentHandlingInstructions VARCHAR(255),
       ShipmentOriginFacilityId VARCHAR(20),
       ShipmentDestinationFacilityId VARCHAR(20),
       ShipmentOriginContactMechId VARCHAR(20),
       ShipmentOriginTelecomNumberId VARCHAR(20),
       ShipmentDestinationContactMechId VARCHAR(20),
       ShipmentDestinationTelecomNumberId VARCHAR(20),
       ShipmentPartyIdTo VARCHAR(20),
       ShipmentPartyIdFrom VARCHAR(20),
       ShipmentAdditionalShippingCharge DECIMAL(18,2),
       ShipmentAddtlShippingChargeDesc VARCHAR(255),
       ShipmentCreatedBy VARCHAR(255),
       ShipmentCreatedAt DATETIME,
       ShipmentUpdatedBy VARCHAR(255),
       ShipmentUpdatedAt DATETIME,
       ShipmentActive TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyOrderIdRemoved TINYINT(1),
       IsPropertyOrderItemSeqIdRemoved TINYINT(1),
       IsPropertyShipGroupSeqIdRemoved TINYINT(1),
       IsPropertyProductIdRemoved TINYINT(1),
       IsPropertyLocatorIdRemoved TINYINT(1),
       IsPropertyAttributeSetInstanceIdRemoved TINYINT(1),
       IsPropertyShipmentItemSeqIdRemoved TINYINT(1),
       IsPropertyFixedAssetIdRemoved TINYINT(1),
       IsPropertyMaintHistSeqIdRemoved TINYINT(1),
       IsPropertyIssuedDateTimeRemoved TINYINT(1),
       IsPropertyIssuedByUserLoginIdRemoved TINYINT(1),
       IsPropertyQuantityRemoved TINYINT(1),
       IsPropertyCancelQuantityRemoved TINYINT(1),
       IsPropertyVersionRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       IsPropertyShipmentShipmentTypeIdRemoved TINYINT(1),
       IsPropertyShipmentStatusIdRemoved TINYINT(1),
       IsPropertyShipmentPrimaryOrderIdRemoved TINYINT(1),
       IsPropertyShipmentPrimaryReturnIdRemoved TINYINT(1),
       IsPropertyShipmentPrimaryShipGroupSeqIdRemoved TINYINT(1),
       IsPropertyShipmentPicklistBinIdRemoved TINYINT(1),
       IsPropertyShipmentEstimatedReadyDateRemoved TINYINT(1),
       IsPropertyShipmentEstimatedShipDateRemoved TINYINT(1),
       IsPropertyShipmentEstimatedShipWorkEffIdRemoved TINYINT(1),
       IsPropertyShipmentEstimatedArrivalDateRemoved TINYINT(1),
       IsPropertyShipmentEstimatedArrivalWorkEffIdRemoved TINYINT(1),
       IsPropertyShipmentLatestCancelDateRemoved TINYINT(1),
       IsPropertyShipmentEstimatedShipCostRemoved TINYINT(1),
       IsPropertyShipmentCurrencyUomIdRemoved TINYINT(1),
       IsPropertyShipmentHandlingInstructionsRemoved TINYINT(1),
       IsPropertyShipmentOriginFacilityIdRemoved TINYINT(1),
       IsPropertyShipmentDestinationFacilityIdRemoved TINYINT(1),
       IsPropertyShipmentOriginContactMechIdRemoved TINYINT(1),
       IsPropertyShipmentOriginTelecomNumberIdRemoved TINYINT(1),
       IsPropertyShipmentDestinationContactMechIdRemoved TINYINT(1),
       IsPropertyShipmentDestinationTelecomNumberIdRemoved TINYINT(1),
       IsPropertyShipmentPartyIdToRemoved TINYINT(1),
       IsPropertyShipmentPartyIdFromRemoved TINYINT(1),
       IsPropertyShipmentAdditionalShippingChargeRemoved TINYINT(1),
       IsPropertyShipmentAddtlShippingChargeDescRemoved TINYINT(1),
       IsPropertyShipmentCreatedByRemoved TINYINT(1),
       IsPropertyShipmentCreatedAtRemoved TINYINT(1),
       IsPropertyShipmentUpdatedByRemoved TINYINT(1),
       IsPropertyShipmentUpdatedAtRemoved TINYINT(1),
       IsPropertyShipmentActiveRemoved TINYINT(1),
       primary key (ShipmentItemIssuanceIdShipmentId, ShipmentItemIssuanceIdItemIssuanceSeqId, ShipmentVersion)
    );
    create table ShipmentPackageContent_RV (
        ShipmentPackageContentIdShipmentPackageIdShipmentId VARCHAR(20) not null,
       ShipmentPackageContentIdShipmentPackageIdShipmentPackageSeqId VARCHAR(20) not null,
       ShipmentPackageContentIdShipmentItemSeqId VARCHAR(20) not null,
       ShipmentPackageVersion BIGINT not null,
       Quantity DECIMAL(18,6),
       SubProductId VARCHAR(20),
       SubProductQuantity DECIMAL(18,6),
       Version BIGINT,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       ShipmentPackageShipmentBoxTypeId VARCHAR(20),
       ShipmentPackageDateCreated DATETIME,
       ShipmentPackageBoxLength DECIMAL(18,6),
       ShipmentPackageBoxHeight DECIMAL(18,6),
       ShipmentPackageBoxWidth DECIMAL(18,6),
       ShipmentPackageDimensionUomId VARCHAR(20),
       ShipmentPackageWeight DECIMAL(18,6),
       ShipmentPackageWeightUomId VARCHAR(20),
       ShipmentPackageInsuredValue DECIMAL(18,2),
       ShipmentPackageCreatedBy VARCHAR(255),
       ShipmentPackageCreatedAt DATETIME,
       ShipmentPackageUpdatedBy VARCHAR(255),
       ShipmentPackageUpdatedAt DATETIME,
       ShipmentPackageActive TINYINT(1),
       ShipmentPackageDeleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (ShipmentPackageContentIdShipmentPackageIdShipmentId, ShipmentPackageContentIdShipmentPackageIdShipmentPackageSeqId, ShipmentPackageContentIdShipmentItemSeqId)
    );
    create table ShipmentPackageContentMvoStateEvents (
        ShipmentPackageContentIdShipmentPackageIdShipmentId VARCHAR(20) not null,
       ShipmentPackageContentIdShipmentPackageIdShipmentPackageSeqId VARCHAR(20) not null,
       ShipmentPackageContentIdShipmentItemSeqId VARCHAR(20) not null,
       ShipmentPackageVersion BIGINT not null,
       StateEventType VARCHAR(255) not null,
       Quantity DECIMAL(18,6),
       SubProductId VARCHAR(20),
       SubProductQuantity DECIMAL(18,6),
       Version BIGINT,
       Active TINYINT(1),
       ShipmentPackageShipmentBoxTypeId VARCHAR(20),
       ShipmentPackageDateCreated DATETIME,
       ShipmentPackageBoxLength DECIMAL(18,6),
       ShipmentPackageBoxHeight DECIMAL(18,6),
       ShipmentPackageBoxWidth DECIMAL(18,6),
       ShipmentPackageDimensionUomId VARCHAR(20),
       ShipmentPackageWeight DECIMAL(18,6),
       ShipmentPackageWeightUomId VARCHAR(20),
       ShipmentPackageInsuredValue DECIMAL(18,2),
       ShipmentPackageCreatedBy VARCHAR(255),
       ShipmentPackageCreatedAt DATETIME,
       ShipmentPackageUpdatedBy VARCHAR(255),
       ShipmentPackageUpdatedAt DATETIME,
       ShipmentPackageActive TINYINT(1),
       ShipmentPackageDeleted TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyQuantityRemoved TINYINT(1),
       IsPropertySubProductIdRemoved TINYINT(1),
       IsPropertySubProductQuantityRemoved TINYINT(1),
       IsPropertyVersionRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       IsPropertyShipmentPackageShipmentBoxTypeIdRemoved TINYINT(1),
       IsPropertyShipmentPackageDateCreatedRemoved TINYINT(1),
       IsPropertyShipmentPackageBoxLengthRemoved TINYINT(1),
       IsPropertyShipmentPackageBoxHeightRemoved TINYINT(1),
       IsPropertyShipmentPackageBoxWidthRemoved TINYINT(1),
       IsPropertyShipmentPackageDimensionUomIdRemoved TINYINT(1),
       IsPropertyShipmentPackageWeightRemoved TINYINT(1),
       IsPropertyShipmentPackageWeightUomIdRemoved TINYINT(1),
       IsPropertyShipmentPackageInsuredValueRemoved TINYINT(1),
       IsPropertyShipmentPackageCreatedByRemoved TINYINT(1),
       IsPropertyShipmentPackageCreatedAtRemoved TINYINT(1),
       IsPropertyShipmentPackageUpdatedByRemoved TINYINT(1),
       IsPropertyShipmentPackageUpdatedAtRemoved TINYINT(1),
       IsPropertyShipmentPackageActiveRemoved TINYINT(1),
       IsPropertyShipmentPackageDeletedRemoved TINYINT(1),
       primary key (ShipmentPackageContentIdShipmentPackageIdShipmentId, ShipmentPackageContentIdShipmentPackageIdShipmentPackageSeqId, ShipmentPackageContentIdShipmentItemSeqId, ShipmentPackageVersion)
    );
    create table OrderItemShipGrpInvReservations (
        OrderItemShipGrpInvResIdOrderId VARCHAR(20) not null,
       OrderItemShipGrpInvResIdShipGroupSeqId DECIMAL(20,0) not null,
       OrderItemShipGrpInvResIdOrderItemSeqId VARCHAR(20) not null,
       OrderItemShipGrpInvResIdProductId VARCHAR(60) not null,
       OrderItemShipGrpInvResIdLocatorId VARCHAR(50) not null,
       OrderItemShipGrpInvResIdAttributeSetInstanceId VARCHAR(50) not null,
       Version BIGINT not null,
       ReserveOrderEnumId VARCHAR(20),
       Quantity DECIMAL(18,6),
       QuantityNotAvailable DECIMAL(18,6),
       ReservedDatetime DATETIME,
       CreatedDatetime DATETIME,
       PromisedDatetime DATETIME,
       CurrentPromisedDate DATETIME,
       Priority CHAR(1),
       SequenceId DECIMAL(20,0),
       OldPickStartDate DATETIME,
       CreatedBy VARCHAR(255),
       UpdatedBy VARCHAR(255),
       Active TINYINT(1),
       Deleted TINYINT(1),
       CreatedAt DATETIME,
       UpdatedAt DATETIME,
       primary key (OrderItemShipGrpInvResIdOrderId, OrderItemShipGrpInvResIdShipGroupSeqId, OrderItemShipGrpInvResIdOrderItemSeqId, OrderItemShipGrpInvResIdProductId, OrderItemShipGrpInvResIdLocatorId, OrderItemShipGrpInvResIdAttributeSetInstanceId)
    );
    create table OrderItemShipGrpInvReservationStateEvents (
        OrderItemShipGrpInvResIdOrderId VARCHAR(20) not null,
       OrderItemShipGrpInvResIdShipGroupSeqId DECIMAL(20,0) not null,
       OrderItemShipGrpInvResIdOrderItemSeqId VARCHAR(20) not null,
       OrderItemShipGrpInvResIdProductId VARCHAR(60) not null,
       OrderItemShipGrpInvResIdLocatorId VARCHAR(50) not null,
       OrderItemShipGrpInvResIdAttributeSetInstanceId VARCHAR(50) not null,
       Version BIGINT not null,
       StateEventType VARCHAR(255) not null,
       ReserveOrderEnumId VARCHAR(20),
       Quantity DECIMAL(18,6),
       QuantityNotAvailable DECIMAL(18,6),
       ReservedDatetime DATETIME,
       CreatedDatetime DATETIME,
       PromisedDatetime DATETIME,
       CurrentPromisedDate DATETIME,
       Priority CHAR(1),
       SequenceId DECIMAL(20,0),
       OldPickStartDate DATETIME,
       Active TINYINT(1),
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       CommandId VARCHAR(255),
       IsPropertyReserveOrderEnumIdRemoved TINYINT(1),
       IsPropertyQuantityRemoved TINYINT(1),
       IsPropertyQuantityNotAvailableRemoved TINYINT(1),
       IsPropertyReservedDatetimeRemoved TINYINT(1),
       IsPropertyCreatedDatetimeRemoved TINYINT(1),
       IsPropertyPromisedDatetimeRemoved TINYINT(1),
       IsPropertyCurrentPromisedDateRemoved TINYINT(1),
       IsPropertyPriorityRemoved TINYINT(1),
       IsPropertySequenceIdRemoved TINYINT(1),
       IsPropertyOldPickStartDateRemoved TINYINT(1),
       IsPropertyActiveRemoved TINYINT(1),
       primary key (OrderItemShipGrpInvResIdOrderId, OrderItemShipGrpInvResIdShipGroupSeqId, OrderItemShipGrpInvResIdOrderItemSeqId, OrderItemShipGrpInvResIdProductId, OrderItemShipGrpInvResIdLocatorId, OrderItemShipGrpInvResIdAttributeSetInstanceId, Version)
    );