
    create table UserRole_RV (
        UserRoleIdUserId VARCHAR(50) not null,
       UserRoleIdRoleId VARCHAR(50) not null,
       UserVersion BIGINT not null,
       Version BIGINT,
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       UpdatedBy VARCHAR(255),
       UpdatedAt DATETIME,
       Active TINYINT(1),
       Deleted TINYINT(1),
       UserUserName VARCHAR(255),
       UserAccessFailedCount INTEGER,
       UserEmail VARCHAR(255),
       UserEmailConfirmed TINYINT(1),
       UserLockoutEnabled TINYINT(1),
       UserLockoutEndDateUtc DATETIME,
       UserPasswordHash VARCHAR(255),
       UserPhoneNumber VARCHAR(255),
       UserPhoneNumberConfirmed TINYINT(1),
       UserTwoFactorEnabled TINYINT(1),
       UserSecurityStamp VARCHAR(255),
       UserCreatedBy VARCHAR(255),
       UserCreatedAt DATETIME,
       UserUpdatedBy VARCHAR(255),
       UserUpdatedAt DATETIME,
       UserActive TINYINT(1),
       UserDeleted TINYINT(1),
       primary key (UserRoleIdUserId, UserRoleIdRoleId)
    );
    create table UserClaim_RV (
        UserClaimIdUserId VARCHAR(50) not null,
       UserClaimIdClaimId INTEGER not null,
       UserVersion BIGINT not null,
       ClaimType VARCHAR(255),
       ClaimValue VARCHAR(255),
       Version BIGINT,
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       UpdatedBy VARCHAR(255),
       UpdatedAt DATETIME,
       Active TINYINT(1),
       Deleted TINYINT(1),
       UserUserName VARCHAR(255),
       UserAccessFailedCount INTEGER,
       UserEmail VARCHAR(255),
       UserEmailConfirmed TINYINT(1),
       UserLockoutEnabled TINYINT(1),
       UserLockoutEndDateUtc DATETIME,
       UserPasswordHash VARCHAR(255),
       UserPhoneNumber VARCHAR(255),
       UserPhoneNumberConfirmed TINYINT(1),
       UserTwoFactorEnabled TINYINT(1),
       UserSecurityStamp VARCHAR(255),
       UserCreatedBy VARCHAR(255),
       UserCreatedAt DATETIME,
       UserUpdatedBy VARCHAR(255),
       UserUpdatedAt DATETIME,
       UserActive TINYINT(1),
       UserDeleted TINYINT(1),
       primary key (UserClaimIdUserId, UserClaimIdClaimId)
    );
    create table UserPermission_RV (
        UserPermissionIdUserId VARCHAR(50) not null,
       UserPermissionIdPermissionId VARCHAR(50) not null,
       UserVersion BIGINT not null,
       Version BIGINT,
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       UpdatedBy VARCHAR(255),
       UpdatedAt DATETIME,
       Active TINYINT(1),
       Deleted TINYINT(1),
       UserUserName VARCHAR(255),
       UserAccessFailedCount INTEGER,
       UserEmail VARCHAR(255),
       UserEmailConfirmed TINYINT(1),
       UserLockoutEnabled TINYINT(1),
       UserLockoutEndDateUtc DATETIME,
       UserPasswordHash VARCHAR(255),
       UserPhoneNumber VARCHAR(255),
       UserPhoneNumberConfirmed TINYINT(1),
       UserTwoFactorEnabled TINYINT(1),
       UserSecurityStamp VARCHAR(255),
       UserCreatedBy VARCHAR(255),
       UserCreatedAt DATETIME,
       UserUpdatedBy VARCHAR(255),
       UserUpdatedAt DATETIME,
       UserActive TINYINT(1),
       UserDeleted TINYINT(1),
       primary key (UserPermissionIdUserId, UserPermissionIdPermissionId)
    );
    create table UserLogin_RV (
        UserLoginIdUserId VARCHAR(50) not null,
       UserLoginIdLoginKeyLoginProvider VARCHAR(255) not null,
       UserLoginIdLoginKeyProviderKey VARCHAR(255) not null,
       UserVersion BIGINT not null,
       Version BIGINT,
       CreatedBy VARCHAR(255),
       CreatedAt DATETIME,
       UpdatedBy VARCHAR(255),
       UpdatedAt DATETIME,
       Active TINYINT(1),
       Deleted TINYINT(1),
       UserUserName VARCHAR(255),
       UserAccessFailedCount INTEGER,
       UserEmail VARCHAR(255),
       UserEmailConfirmed TINYINT(1),
       UserLockoutEnabled TINYINT(1),
       UserLockoutEndDateUtc DATETIME,
       UserPasswordHash VARCHAR(255),
       UserPhoneNumber VARCHAR(255),
       UserPhoneNumberConfirmed TINYINT(1),
       UserTwoFactorEnabled TINYINT(1),
       UserSecurityStamp VARCHAR(255),
       UserCreatedBy VARCHAR(255),
       UserCreatedAt DATETIME,
       UserUpdatedBy VARCHAR(255),
       UserUpdatedAt DATETIME,
       UserActive TINYINT(1),
       UserDeleted TINYINT(1),
       primary key (UserLoginIdUserId, UserLoginIdLoginKeyLoginProvider, UserLoginIdLoginKeyProviderKey)
    );